# For conda build
package:
  name: rmgdatabase
  version: "0" # set by build.sh, which gets it from version.py file

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} # number of commits since last git tag (which should be last change to __version__)
 
requirements:
  build:
    - python
  run:
    - python

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-database
  license: MIT
  summary: "Database for RMG: a program for automatically generating kinetic models of chemical reaction mechanisms."
