# For conda build
package:
  name: rmgdatabase
  version: "1.0.2"

source:
  path: .

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-database
  license: MIT
  summary: "Database for RMG: a program for automatically generating kinetic models of chemical reaction mechanisms."
