#!/usr/bin/env python
# encoding: utf-8

name = "XY_elimination_hydroxyl/groups"
shortDesc = ""
longDesc = """
                R
                |
R - R*2 - R*3 - C*4     <-->  R - R*2 = R*3  +  X*1 - Y*6  +  O*5 = C*4 - R
    |           |
    X*1   Y*6 - O*5

X = H, F, Cl, Br
Y = H, F, Cl, Br
"""

template(reactants=["XRRCOOY"], products=["R=R","XY","CO2"], ownReverse=False)

reverse = "XY_addition_carboxyl"
reversible = True

reactantNum = 1

productNum = 3

autoGenerated = False

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['BREAK_BOND', '*5', 1, '*6'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*4', 1, '*5'],
    ['FORM_BOND', '*1', 1, '*6'],
])

entry(
    index = 0,
    label = "XRRCOOY",
    group = 
"""
1 *1 [H,F1s,Cl1s,Br1s] u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 [H,F1s,Cl1s,Br1s] u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "HRRCOOH",
    group = 
"""
1 *1 H                 u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "FRRCOOY",
    group = 
"""
1 *1 F1s               u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 [H,F1s,Cl1s,Br1s] u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "ClRRCOOY",
    group = 
"""
1 *1 Cl1s              u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 [H,F1s,Cl1s,Br1s] u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "BrRRCOOY",
    group = 
"""
1 *1 Br1s              u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 [H,F1s,Cl1s,Br1s] u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "FRRCOOH",
    group = 
"""
1 *1 F1s               u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "ClRRCOOH",
    group = 
"""
1 *1 Cl1s              u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "BrRRCOOH",
    group = 
"""
1 *1 Br1s              u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)


entry(
    index = 8,
    label = "FCCCOOH",
    group = 
"""
1 *1 F1s               u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 C                 u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "FCOCOOH",
    group = 
"""
1 *1 F1s               u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 O                 u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "ClCCCOOH",
    group = 
"""
1 *1 Cl1s              u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 C                 u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "ClCOCOOH",
    group = 
"""
1 *1 Cl1s              u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 O                 u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "BrCCCOOH",
    group = 
"""
1 *1 Br1s              u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 C                 u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "BrCOCOOH",
    group = 
"""
1 *1 Br1s              u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 O                 u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "FCCF2COOH",
    group = 
"""
1 *1 F1s               u0 {2,S}
2 *2 C                 u0 {1,S} {3,S}
3 *3 C                 u0 {2,S} {4,S} {7,S} {8,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
7  F1s                 u0 {3,S}
8  F1s                 u0 {3,S}
""",
    kinetics = None,
)

tree(
"""
L1: XRRCOOY
    L2: HRRCOOH
    L2: FRRCOOY
        L3: FRRCOOH
            L4: FCCCOOH
                L5: FCCF2COOH
            L4: FCOCOOH
    L2: ClRRCOOY
        L3: ClRRCOOH
            L4: ClCCCOOH
            L4: ClCOCOOH
    L2: BrRRCOOY
        L3: BrRRCOOH
            L4: BrCCCOOH
            L4: BrCOCOOH
"""
)

forbidden(
    label = "H2_elimination",
    group = 
"""
1 *1 H                 u0 {2,S}
2 *2 R!H               u0 {1,S} {3,S}
3 *3 R!H               u0 {2,S} {4,S}
4 *4 C                 u0 {3,S} {5,S}
5 *5 O                 u0 {4,S} {6,S}
6 *6 H                 u0 {5,S}
""",
    shortDesc = u"""""",
    longDesc = 
u"""
This group forbids H2 elimination where X = Y = H.

The barrier is too high

CH3CH2COOH <=> C2H4 + H2 + CO2
kinetics = Arrhenius(
    A = (205359, 's^-1'),
    n = 2.17099,
    Ea = (342.051, 'kJ/mol'),
    T0 = (1, 'K'),
    Tmin = (298, 'K'),
    Tmax = (2500, 'K'),
    comment = 'Fitted to 50 data points; dA = *|/ 2.11965, dn = +|- 0.0986994, dEa = +|- 0.537118 kJ/mol',
)

Calculated at DFT level (M062XD3/JUN-CC-PVTZ) with Gaussian 16 with RRHO approx
Coordinates for TS in Input Orientation (angstroms):
  H    1.6460   -0.6292   -0.0004
  C    1.3976    0.9388    0.0003
  C    0.0496    1.2643   -0.0002
  C   -1.1556   -0.2720    0.0001
  O   -2.2477    0.1918    0.0002
  O   -0.5321   -1.3076    0.0001
  H    1.9759    0.9869    0.9145
  H    1.9768    0.9876   -0.9131
  H   -0.3684    1.6608    0.9146
  H   -0.3678    1.6604   -0.9156
  H    0.9157   -1.0188   -0.0001
""",
)

