#!/usr/bin/env python
# encoding: utf-8

name = "furfuryl_oxidation_Wang_40_rxns"
shortDesc = "40_rxns"
longDesc = """
Experimental and kinetic modeling studies of low- to moderate-temperature oxidation of 2-furfuryl alcohol in a jet-stirred reactor
"""
autoGenerated=False
entry(
    index = 0,
    label = "mf22j + oh <=> FFA",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 1,
    label = "f2choh + h <=> FFA",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 2,
    label = "mf22oj + h <=> FFA",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.43e+12,'cm^3/(mol*s)'), n=0.52, Ea=(50.19,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(4.66e+41,'cm^6/(mol^2*s)'), n=-7.44, Ea=(14079.8,'cal/mol'), T0=(1,'K')), alpha=0.7, T3=(100,'K'), T1=(90000,'K'), T2=(10000,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 12.0, 'O=C=O': 3.6, '[Ar]': 0.7, '[C-]#[O+]': 1.75, '[H][H]': 2.0}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 3,
    label = "FFA <=> f2j + ch2oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.95e+27,'s^-1'), n=-3.16, Ea=(107450,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 4,
    label = "FFA <=> furfural + h2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.24e+11,'s^-1'), n=0.1, Ea=(91010,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 5,
    label = "FFA <=> FFA2acar",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.09e+08,'s^-1'), n=1.02, Ea=(73630,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 6,
    label = "FFA <=> FFA3bcar",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.5e+06,'s^-1'), n=1.92, Ea=(67668.4,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 7,
    label = "FFA <=> FFA4bcar",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+11,'s^-1'), n=0.68, Ea=(70167.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 8,
    label = "FFA <=> FFA5acar",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.1e+10,'s^-1'), n=0.98, Ea=(65967.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 9,
    label = "FFA <=> p24de1o5oh-c",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(4.5e+07,'s^-1'), n=1.8, Ea=(74364.5,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.3e+08,'s^-1'), n=1.58, Ea=(76464.4,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified

Originally from reaction library: Unclassified
""",
)

entry(
    index = 10,
    label = "FFA + o2 <=> f2choh + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+12,'cm^3/(mol*s)'), n=0, Ea=(34000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 11,
    label = "FFA + h <=> f2choh + h2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8e+13,'cm^3/(mol*s)'), n=0, Ea=(6400,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 12,
    label = "FFA + o <=> f2choh + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.2e+11,'cm^3/(mol*s)'), n=0, Ea=(-2000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 13,
    label = "FFA + oh <=> f2choh + h2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.9e+09,'cm^3/(mol*s)'), n=1, Ea=(-1100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 14,
    label = "FFA + ho2 <=> f2choh + h2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.5e-05,'cm^3/(mol*s)'), n=5.26, Ea=(8268,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 15,
    label = "FFA + ch3 <=> f2choh + ch4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+12,'cm^3/(mol*s)'), n=0, Ea=(9100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 16,
    label = "FFA + c3h3 <=> f2choh + c3h4-p",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+12,'cm^3/(mol*s)'), n=0, Ea=(13100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 17,
    label = "FFA + c3h5-a <=> f2choh + c3h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+12,'cm^3/(mol*s)'), n=0, Ea=(13100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 18,
    label = "FFA + c4h5-i <=> f2choh + c4h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+12,'cm^3/(mol*s)'), n=0, Ea=(13100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 19,
    label = "FFA + c4h5-n <=> f2choh + c4h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+12,'cm^3/(mol*s)'), n=0, Ea=(13100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 20,
    label = "FFA + c5h5 <=> f2choh + c5h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+12,'cm^3/(mol*s)'), n=0, Ea=(9100,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 21,
    label = "FFA + c6h5 <=> f2choh + c6h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.2e+13,'cm^3/(mol*s)'), n=0, Ea=(10000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 22,
    label = "FFA + ch2oh <=> f2choh + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(60,'cm^3/(mol*s)'), n=2.95, Ea=(12000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 23,
    label = "FFA + h <=> mf22oj + h2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(945,'cm^3/(mol*s)'), n=3.14, Ea=(8701,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 24,
    label = "FFA + o <=> mf22oj + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00146,'cm^3/(mol*s)'), n=4.73, Ea=(1727,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 4.99E-05             4.891            -9.750E+02/"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 4.99E-05             4.891            -9.750E+02/
""",
)

entry(
    index = 25,
    label = "FFA + oh <=> mf22oj + h2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+10,'cm^3/(mol*s)'), n=0.8, Ea=(2534,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 9.038E+09            0.896             1.612E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 9.038E+09            0.896             1.612E+04 /
""",
)

entry(
    index = 26,
    label = "FFA + o2 <=> mf22oj + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.980E+12           -0.146            -7.791E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.980E+12           -0.146            -7.791E+03 /
""",
)

entry(
    index = 27,
    label = "FFA + ho2 <=> mf22oj + h2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.47e-07,'cm^3/(mol*s)'), n=5.3, Ea=(10530,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 28,
    label = "FFA + ch3 <=> mf22oj + ch4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.02,'cm^3/(mol*s)'), n=3.57, Ea=(8221,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 29,
    label = "FFA + hco <=> mf22oj + ch2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(34000,'cm^3/(mol*s)'), n=2.5, Ea=(13500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 30,
    label = "FFA + ch2oh <=> mf22oj + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(120,'cm^3/(mol*s)'), n=2.76, Ea=(10800,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 31,
    label = "FFA + ch3o <=> mf22oj + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.3e+10,'cm^3/(mol*s)'), n=0, Ea=(2900,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 32,
    label = "FFA + c2h5 <=> mf22oj + c2h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(9200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 33,
    label = "FFA + h <=> furan + ch2oh",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([0.01,0.1,1,2.5,10,100],'atm'), arrhenius=[Arrhenius(A=(5.93e+17,'cm^3/(mol*s)'), n=-1.13, Ea=(10160.3,'cal/mol'), T0=(1,'K')), Arrhenius(A=(6.31e+15,'cm^3/(mol*s)'), n=-0.49, Ea=(10818.3,'cal/mol'), T0=(1,'K')), Arrhenius(A=(6.25e+15,'cm^3/(mol*s)'), n=-0.44, Ea=(12156.5,'cal/mol'), T0=(1,'K')), Arrhenius(A=(6.28e+15,'cm^3/(mol*s)'), n=-0.43, Ea=(12614.1,'cal/mol'), T0=(1,'K')), Arrhenius(A=(7.55e+15,'cm^3/(mol*s)'), n=-0.43, Ea=(13614.5,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.47e+21,'cm^3/(mol*s)'), n=-1.92, Ea=(19574.5,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 34,
    label = "FFA + h <=> chchch2ch2oh + co",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([0.01,0.1,1,2.5,10,100],'atm'), arrhenius=[Arrhenius(A=(3.28e+24,'cm^3/(mol*s)'), n=-3.07, Ea=(13756.3,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.22e+31,'cm^3/(mol*s)'), n=-4.83, Ea=(20365.1,'cal/mol'), T0=(1,'K')), Arrhenius(A=(3.52e+33,'cm^3/(mol*s)'), n=-5.39, Ea=(25716.6,'cal/mol'), T0=(1,'K')), Arrhenius(A=(6.3e+31,'cm^3/(mol*s)'), n=-4.83, Ea=(26504.1,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.69e+27,'cm^3/(mol*s)'), n=-3.43, Ea=(27005.6,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.27e+17,'cm^3/(mol*s)'), n=-0.43, Ea=(26869.3,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 35,
    label = "FFA + h <=> ch2chchco + ch2oh",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([0.01,0.1,1,2.5,10,100],'atm'), arrhenius=[Arrhenius(A=(1.07e+39,'cm^3/(mol*s)'), n=-6.67, Ea=(30845.7,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.5e+47,'cm^3/(mol*s)'), n=-8.88, Ea=(38568.1,'cal/mol'), T0=(1,'K')), Arrhenius(A=(5.03e+47,'cm^3/(mol*s)'), n=-8.89, Ea=(42758.2,'cal/mol'), T0=(1,'K')), Arrhenius(A=(8.28e+44,'cm^3/(mol*s)'), n=-8.04, Ea=(42836.8,'cal/mol'), T0=(1,'K')), Arrhenius(A=(6.18e+36,'cm^3/(mol*s)'), n=-5.65, Ea=(40636.9,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.44e+32,'cm^3/(mol*s)'), n=-4.18, Ea=(44350.8,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 36,
    label = "FFA + h <=> ch2chchch2oh + co",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([0.01,0.1,1,2.5,10,100],'atm'), arrhenius=[Arrhenius(A=(1.07e+47,'cm^3/(mol*s)'), n=-9.58, Ea=(29916.8,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.48e+51,'cm^3/(mol*s)'), n=-10.63, Ea=(36021.6,'cal/mol'), T0=(1,'K')), Arrhenius(A=(5.31e+47,'cm^3/(mol*s)'), n=-9.49, Ea=(38642.7,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.28e+43,'cm^3/(mol*s)'), n=-8.11, Ea=(37934.3,'cal/mol'), T0=(1,'K')), Arrhenius(A=(4.8e+41,'cm^3/(mol*s)'), n=-7.57, Ea=(41808.8,'cal/mol'), T0=(1,'K')), Arrhenius(A=(7.91e+39,'cm^3/(mol*s)'), n=-6.79, Ea=(51713.9,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 37,
    label = "FFA + oh <=> FFA22oh3j",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(11050,'cm^3/(mol*s)'), n=2.45, Ea=(-7251,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 38,
    label = "FFA + oh <=> FFA25oh4j",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(11050,'cm^3/(mol*s)'), n=2.45, Ea=(-7251,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 39,
    label = "FFA + oh <=> FFA24oh5j",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(226000,'cm^3/(mol*s)'), n=2.14, Ea=(-1900,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 40,
    label = "FFA + oh <=> FFA23oh2j",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(297000,'cm^3/(mol*s)'), n=2.09, Ea=(-3200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

