#!/usr/bin/env python
# encoding: utf-8

name = "Singlet_Carbene_Intra_Disproportionation/groups"
shortDesc = "Convert a singlet carbene to a closed-shell molecule through a concerted 1,2-H shift + 1,2-bond formation"
longDesc = """
Reaction site *1 should always be a singlet in this family.
"""

template(reactants=["Root"], products=["CH_C_unsaturated"], ownReverse=False)

reverse = "SingletCarbenefromMultipleBond"
reversible = True

reactantNum = 1

productNum = 1

autoGenerated = True

recipe(actions=[
    ['LOSE_PAIR', '*1', '1'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*1', 1, '*2'],
])

boundaryAtoms = ["*1", "*2"]

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C        u0 {2,S} {3,[S,D]}
2 *3 [H,Val7] u0 {1,S}
3 *1 C        u0 p1 c0 {1,[S,D]}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_1C-inRing",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,[S,D]}
2 *3 H u0 {1,S}
3 *1 C u0 p1 c0 {1,[S,D]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_Sp-4R!H-1C",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,S} {4,S}
2 *3 H u0 {1,S}
3 *1 C u0 p1 c0 {1,S}
4    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_Sp-4R!H-1C_Ext-4R!H-R_Ext-4R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,S} {4,S}
2 *3 H   u0 r0 {1,S}
3 *1 C   u0 p1 c0 r1 {1,S}
4    C   u0 r1 {1,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    R!H ux {4,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_N-Sp-4R!H-1C",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,[S,D]} {4,[B,D,T,Q]}
2 *3 H u0 {1,S}
3 *1 C u0 p1 c0 {1,[S,D]}
4    C ux {1,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_N-Sp-4R!H-1C_Ext-4R!H-R_Ext-5R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,[S,D]} {4,[B,D,T,Q]}
2 *3 H u0 {1,S}
3 *1 C u0 p1 c0 r1 {1,[S,D]} {5,[S,D,T,B,Q]}
4    C ux r1 {1,[B,D,T,Q]}
5    C ux r1 {3,[S,D,T,B,Q]} {6,S}
6    C u0 r1 {5,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_N-Sp-4R!H-1C_Ext-4R!H-R_Ext-5R!H-R_Ext-5R!H-R_N-Sp-6R!H-5R!H",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,[S,D]} {4,[B,D,T,Q]}
2 *3 H u0 {1,S}
3 *1 C u0 p1 c0 r1 {1,[S,D]} {5,[S,D,T,B,Q]}
4    C ux r1 {1,[B,D,T,Q]}
5    C ux r1 {3,[S,D,T,B,Q]} {6,[B,D,T,Q]}
6    C u0 r1 {5,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-1C-inRing",
    group = 
"""
1 *2 C        u0 r0 {2,S} {3,S}
2 *3 [H,Val7] u0 r0 {1,S}
3 *1 C        u0 p1 c0 {1,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_1C-inRing
        L3: Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_Sp-4R!H-1C
            L4: Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_Sp-4R!H-1C_Ext-4R!H-R_Ext-4R!H-R
        L3: Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_N-Sp-4R!H-1C
            L4: Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_N-Sp-4R!H-1C_Ext-4R!H-R_Ext-5R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H
            L4: Root_1C-inRing_Ext-3C-R_Ext-4R!H-R_N-Sp-4R!H-1C_Ext-4R!H-R_Ext-5R!H-R_Ext-5R!H-R_N-Sp-6R!H-5R!H
    L2: Root_N-1C-inRing
"""
)

