#!/usr/bin/env python
# encoding: utf-8

name = "1,3_sigmatropic_rearrangement/groups"
shortDesc = ""
longDesc = """
20211010: The ketoenol family was generalized to accept R!H rather than previously only accepting O or S.
The family name was also updated to 1,3_sigmatropic_rearrangement to reflect the newly extended reaction template.


20180202: Sulfur was added to this family and is treated the same as oxygen.
https://github.com/ReactionMechanismGenerator/RMG-database/commit/9e9d300b3a0fce1bbb9aa138b2990b264fb1e37b
Ideally we would like to branch this into a new family "R=RSR <=> RRR=S"
once relevant kinetic data is available
"""

template(reactants=["Root"], products=["Root"], ownReverse=True)

reversible = True

reverseMap = {'*1': '*3', '*3': '*1'}

reactantNum = 1

productNum = 1

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*4', 1, '*1'],
])

boundaryAtoms = ["*2", "*3"]

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 R!H u0 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_1R!H-inRing",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_1R!H-inRing_4R->N",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 N   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_1R!H-inRing_N-4R->N",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 R!H   u0 {1,S} {4,S}
3 *1 R!H   u0 {1,D}
4 *4 [C,H] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_1R!H-inRing_N-4R->N_2R!H->O",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 O     u0 {1,S} {4,S}
3 *1 R!H   u0 {1,D}
4 *4 [C,H] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 O     u0 {1,S} {4,S}
3 *1 R!H   u0 r1 {1,D}
4 *4 [C,H] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing_Ext-3R!H-R_5R!H->C",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 O     u0 {1,S} {4,S}
3 *1 R!H   u0 r1 {1,D} {5,[S,D,T,B,Q]}
4 *4 [C,H] u0 {2,S}
5    C     ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing_Ext-3R!H-R_5R!H->C_Ext-1R!H-R",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 O     u0 {1,S} {4,S}
3 *1 R!H   u0 r1 {1,D} {5,[S,D,T,B,Q]}
4 *4 [C,H] u0 {2,S}
5    C     ux r1 {3,[S,D,T,B,Q]}
6    R!H   ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing_Ext-3R!H-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r1 {2,S} {3,D}
2 *3 O                      u0 {1,S} {4,S}
3 *1 R!H                    u0 r1 {1,D} {5,S}
4 *4 [C,H]                  u0 {2,S}
5    [P,Si,F,I,Br,Cl,O,S,N] u0 r1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_1R!H-inRing_N-4R->N_2R!H->O_N-3R!H-inRing",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 O     u0 {1,S} {4,S}
3 *1 R!H   u0 r0 {1,D}
4 *4 [C,H] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 [C,N] u0 {1,S} {4,S}
3 *1 R!H   u0 {1,D}
4 *4 [C,H] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 [C,N] u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 R!H   u0 {1,D}
4 *4 H     u0 {2,S}
5    R!H   ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 [C,N] u0 {1,S} {4,S} {5,S}
3 *1 R!H   u0 {1,D}
4 *4 H     u0 {2,S}
5    R!H   ux {2,S}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_3R!H->C",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S} {5,S}
3 *1 C u0 {1,D}
4 *4 H u0 {2,S}
5    C ux {2,S}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_3R!H->C_Ext-5R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 C   u0 r1 {1,S} {4,S} {5,S}
3 *1 C   u0 r1 {1,D}
4 *4 H   u0 {2,S}
5    C   ux r1 {2,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
7    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 [C,N] u0 {1,S} {4,S} {5,S}
3 *1 [O,N] u0 {1,D}
4 *4 H     u0 {2,S}
5    R!H   ux {2,S}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_2CN->C",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 C     u0 r1 {1,S} {4,S} {5,S}
3 *1 [O,N] u0 {1,D}
4 *4 H     u0 r0 {2,S}
5    R!H   u0 r1 {2,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_N-2CN->C",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S} {5,S}
3 *1 N   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {2,S}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_N-2CN->C_Ext-5R!H-R_Ext-6R!H-R_Ext-6R!H-R_Ext-6R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 N   u0 r1 {1,S} {4,S} {5,S}
3 *1 N   u0 r1 {1,D} {6,[S,D,T,B,Q]}
4 *4 H   u0 {2,S}
5    R!H ux r1 {2,S}
6    C   ux r1 {3,[S,D,T,B,Q]} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
7    R!H ux {6,[S,D,T,B,Q]}
8    R!H ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_N-2CN->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 N   u0 r1 {1,S} {4,S} {5,S}
3 *1 N   u0 r1 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux r1 {2,S}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_N-Sp-5R!H-2CN",
    group = 
"""
1 *2 C     u0 r1 {2,S} {3,D}
2 *3 [C,N] u0 r1 {1,S} {4,S} {5,[B,D,T,Q]}
3 *1 R!H   u0 {1,D}
4 *4 H     u0 r0 {2,S}
5    R!H   u0 r1 {2,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S} {5,D}
5    C   u0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D} {6,S}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S} {5,D}
5    C   u0 {4,D}
6    C   u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C_Ext-1R!H-R_3R!H->O",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D} {6,S}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
6    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C_Ext-1R!H-R_N-3R!H->O",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D} {6,S}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
6    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r1 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 R!H                    u0 {1,D}
4 *4 C                      u0 r1 {2,S} {5,D}
5    [P,Si,F,I,Br,Cl,O,S,N] u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_N-1R!H-inRing",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_N-1R!H-inRing_2R!H->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 R u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_N-1R!H-inRing_2R!H->C_4R->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 C u0 r0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_N-1R!H-inRing_2R!H->C_N-4R->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_N-1R!H-inRing_2R!H->C_N-4R->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 C   u0 {1,S} {4,S}
3 *1 O   u0 r0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_N-1R!H-inRing_N-2R!H->C",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 [O,S,N] u0 {1,S} {4,S}
3 *1 R!H     u0 {1,D}
4 *4 R       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_N-1R!H-inRing_N-2R!H->C_3R!H->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 C u0 {1,D}
4 *4 R u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_N-1R!H-inRing_N-2R!H->C_3R!H->C_4R->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 r0 {1,S} {4,S}
3 *1 C u0 r0 {1,D}
4 *4 C u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_N-1R!H-inRing_N-2R!H->C_3R!H->C_N-4R->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 C u0 {1,D}
4 *4 H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_N-1R!H-inRing_N-2R!H->C_3R!H->C_N-4R->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O   u0 {1,S} {4,S}
3 *1 C   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 [O,S,N] u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 R       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 R       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_4R->N",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 N       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 [C,H]   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 C       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_5R!H->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 {2,S} {5,[S,D,T,B,Q]}
5    O ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_5R!H->O_Ext-4C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 r0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 C   u0 r0 {2,S} {5,D} {6,[S,D,T,B,Q]}
5    O   ux r0 {4,D}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_5R!H->O_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 C   u0 {2,S} {5,[S,D,T,B,Q]}
5    O   ux {4,[S,D,T,B,Q]}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 {1,S} {4,S}
3 *1 [O,S,N]                u0 {1,D}
4 *4 C                      u0 {2,S} {5,[S,D,T,B,Q]}
5    [P,Si,F,I,Br,Cl,C,S,N] ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 [O,S,N]                u0 {1,D}
4 *4 C                      u0 {2,S} {5,[S,D,T,B,Q]}
5    [P,Si,F,I,Br,Cl,C,S,N] ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_3NOS->O",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 O                      u0 {1,D}
4 *4 C                      u0 {2,S} {5,D}
5    [P,Si,F,I,Br,Cl,C,S,N] ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_3NOS->O_5BrCClFINPSSi->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C ux r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_3NOS->O_N-5BrCClFINPSSi->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    N ux r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 N                      u0 {1,D}
4 *4 C                      u0 {2,S} {5,[S,D,T,B,Q]}
5    [P,Si,F,I,Br,Cl,C,S,N] ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O_5BrCClFINPSSi->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S} {5,[S,D,T,B,Q]}
5    C u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O_5BrCClFINPSSi->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 N   u0 r1 {1,S} {4,S}
3 *1 N   u0 r0 {1,D}
4 *4 C   u0 r1 {2,S} {5,[S,D,T,B,Q]}
5    C   u0 r1 {4,[S,D,T,B,Q]}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O_N-5BrCClFINPSSi->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    N ux r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_N-2N-inRing",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r0 {1,S} {4,S}
3 *1 [O,S,N]                u0 {1,D}
4 *4 C                      u0 {2,S} {5,D}
5    [P,Si,F,I,Br,Cl,C,S,N] ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 H       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 [O,S,N] u0 {1,D}
4 *4 H       u0 {2,S}
5    C       ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-1R!H-R",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 N       u0 {1,S} {4,S} {5,S}
3 *1 [O,S,N] u0 r0 {1,D}
4 *4 H       u0 {2,S}
5    C       u0 r0 {2,S}
6    R!H     ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 57,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-5R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 N       u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 [O,S,N] u0 {1,D}
4 *4 H       u0 {2,S}
5    C       ux {2,[S,D,T,B,Q]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H     ux {5,[S,D,T,B,Q]}
7    R!H     ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 58,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-5R!H-R_Ext-5R!H-R_3NOS->O",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    C   ux {2,[S,D,T,B,Q]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
7    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 59,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-5R!H-R_Ext-5R!H-R_N-3NOS->O",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 N   u0 {1,D}
4 *4 H   u0 {2,S}
5    C   ux {2,[S,D,T,B,Q]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
7    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 60,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_3NOS->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
5    C ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 61,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_3NOS->O_Ext-5R!H-R_6R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
5    C ux {2,[S,D,T,B,Q]} {6,D}
6    N u0 r0 {5,D}
""",
    kinetics = None,
)

entry(
    index = 62,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_3NOS->O_Ext-5R!H-R_N-6R!H->N",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 O                      u0 {1,D}
4 *4 H                      u0 {2,S}
5    C                      ux {2,[S,D,T,B,Q]} {6,D}
6    [P,Si,F,I,Br,Cl,O,C,S] u0 r0 {5,D}
""",
    kinetics = None,
)

entry(
    index = 63,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_N-3NOS->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 N u0 {1,D}
4 *4 H u0 {2,S}
5    C ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 64,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 65,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 66,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]} {6,S}
6    R!H ux {5,S}
""",
    kinetics = None,
)

entry(
    index = 67,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]} {6,S} {7,[S,D,T,B,Q]}
6    R!H u0 {5,S}
7    R!H u0 {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 68,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-5R!H-R_5R!H->C",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    C   ux {1,[S,D,T,B,Q]} {6,S} {7,[S,D,T,B,Q]}
6    R!H u0 {5,S}
7    R!H u0 {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 69,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-5R!H-R_N-5R!H->C",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N     u0 {1,S} {4,S}
3 *1 O     u0 {1,D}
4 *4 H     u0 {2,S}
5    [O,N] ux {1,[S,D,T,B,Q]} {6,S} {7,[S,D,T,B,Q]}
6    R!H   u0 {5,S}
7    R!H   u0 {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 70,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_7R!H->N",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]} {6,S}
6    C   ux {5,S} {7,[S,D,T,B,Q]}
7    N   ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 71,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_7R!H->N_5R!H->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
5    O ux r0 {1,[S,D,T,B,Q]} {6,S}
6    C ux r0 {5,S} {7,[S,D,T,B,Q]}
7    N ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 72,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_7R!H->N_N-5R!H->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
5    N ux r0 {1,[S,D,T,B,Q]} {6,S}
6    C ux r0 {5,S} {7,[S,D,T,B,Q]}
7    N ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 73,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_N-7R!H->N",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D} {5,S}
2 *3 N                      u0 r0 {1,S} {4,S}
3 *1 O                      u0 r0 {1,D}
4 *4 H                      u0 r0 {2,S}
5    R!H                    u0 {1,S} {6,S}
6    C                      u0 {5,S} {7,D}
7    [P,Si,F,I,Br,Cl,O,C,S] u0 r0 {6,D}
""",
    kinetics = None,
)

entry(
    index = 74,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_N-Sp-6R!H-5R!H",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 N   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 H   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]} {6,[B,D,T,Q]}
6    R!H u0 {5,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 75,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-3NOS-R_Ext-5R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 N   u0 {1,D} {5,[S,D,T,B,Q]}
4 *4 H   u0 {2,S}
5    C   ux {3,[S,D,T,B,Q]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
7    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 76,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 [O,S]   u0 {1,S} {4,S}
3 *1 [O,S,N] u0 {1,D}
4 *4 R       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 77,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_3NOS->S",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 S u0 {1,D}
4 *4 H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 78,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_3NOS->S_Ext-1R!H-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,S}
2 *3 O u0 {1,S} {4,S}
3 *1 S u0 {1,D}
4 *4 H u0 {2,S}
5    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 79,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_3NOS->S_Ext-1R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,S}
2 *3 O   u0 r0 {1,S} {4,S}
3 *1 S   u0 {1,D}
4 *4 H   u0 r0 {2,S}
5    C   u0 r0 {1,S} {6,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 80,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D}
2 *3 [O,S] u0 {1,S} {4,S}
3 *1 [O,N] u0 {1,D}
4 *4 R     u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 81,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 R u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 82,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 {1,D}
4 *4 R   u0 {2,S}
5    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 83,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_Ext-3NO-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,S}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 r0 {1,D} {6,[S,D,T,B,Q]}
4 *4 R   u0 {2,S}
5    R!H u0 {1,S}
6    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 84,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 R u0 {2,S}
5    N ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 85,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_4R->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,S}
2 *3 O u0 r0 {1,S} {4,S}
3 *1 N u0 r0 {1,D}
4 *4 C u0 r0 {2,S}
5    N u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 86,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 H u0 {2,S}
5    N ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 87,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 H u0 {2,S}
5    N ux {1,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
6    C ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 88,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_7R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 H u0 {2,S}
5    N ux {1,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
6    C ux {5,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
7    N u0 {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 89,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_N-7R!H->N",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D} {5,S}
2 *3 O                      u0 {1,S} {4,S}
3 *1 N                      u0 {1,D}
4 *4 H                      u0 {2,S}
5    N                      u0 {1,S} {6,S}
6    C                      u0 {5,S} {7,[S,D,T,B,Q]}
7    [P,Si,F,I,Br,Cl,O,C,S] ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 90,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_N-7R!H->N_5N-inRing",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D} {5,S}
2 *3 O                      u0 r0 {1,S} {4,S}
3 *1 N                      u0 r0 {1,D}
4 *4 H                      u0 r0 {2,S}
5    N                      u0 r1 {1,S} {6,S}
6    C                      u0 {5,S} {7,[S,D,T,B,Q]}
7    [P,Si,F,I,Br,Cl,O,C,S] ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 91,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_N-7R!H->N_N-5N-inRing",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D} {5,S}
2 *3 O                      u0 r0 {1,S} {4,S}
3 *1 N                      u0 r0 {1,D}
4 *4 H                      u0 r0 {2,S}
5    N                      u0 r0 {1,S} {6,S}
6    C                      u0 {5,S} {7,[S,D,T,B,Q]}
7    [P,Si,F,I,Br,Cl,O,C,S] ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 92,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O     u0 {1,S} {4,S}
3 *1 N     u0 {1,D}
4 *4 H     u0 {2,S}
5    [O,C] ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 93,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N_Ext-5CO-R_Ext-5CO-R",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O     u0 {1,S} {4,S}
3 *1 N     u0 {1,D}
4 *4 H     u0 {2,S}
5    [O,C] ux {1,[S,D,T,B,Q]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H   ux {5,[S,D,T,B,Q]}
7    R!H   ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 94,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N_5CO->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 H u0 {2,S}
5    O ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 95,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N_N-5CO->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 H u0 {2,S}
5    C ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 96,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D} {5,[S,D,T,B,Q]}
4 *4 H u0 {2,S}
5    C ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 97,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R_Ext-5R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 {1,D} {5,[S,D,T,B,Q]}
4 *4 H   u0 {2,S}
5    C   ux {3,[S,D,T,B,Q]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
7    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 98,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R_Ext-5R!H-R_6R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 r0 {1,S} {4,S}
3 *1 N u0 r0 {1,D} {5,S}
4 *4 H u0 r0 {2,S}
5    C u0 r0 {3,S} {6,D}
6    N u0 r0 {5,D}
""",
    kinetics = None,
)

entry(
    index = 99,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R_Ext-5R!H-R_N-6R!H->N",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 O                      u0 r0 {1,S} {4,S}
3 *1 N                      u0 r0 {1,D} {5,S}
4 *4 H                      u0 r0 {2,S}
5    C                      u0 r0 {3,S} {6,D}
6    [P,Si,F,I,Br,Cl,O,C,S] u0 r0 {5,D}
""",
    kinetics = None,
)

entry(
    index = 100,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-4R-R_5R!H->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S} {5,D}
5    O ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 101,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-4R-R_5R!H->O_Ext-4R-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 {1,D}
4 *4 C   u0 {2,S} {5,D} {6,[S,D,T,B,Q]}
5    O   ux {4,D}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 102,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-4R-R_N-5R!H->O",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 O                      u0 r0 {1,S} {4,S}
3 *1 N                      u0 r0 {1,D}
4 *4 C                      u0 r0 {2,S} {5,D}
5    [P,Si,F,I,Br,Cl,C,S,N] u0 r0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 103,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_N-2OS->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 S u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 104,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_N-2OS->O_Ext-1R!H-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {5,S}
2 *3 S u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 H u0 {2,S}
5    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 105,
    label = "Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_N-2OS->O_Ext-1R!H-R_Ext-5R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,S}
2 *3 S   u0 {1,S} {4,S}
3 *1 O   u0 r0 {1,D}
4 *4 H   u0 {2,S}
5    C   u0 r0 {1,S} {6,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_1R!H-inRing
        L3: Root_1R!H-inRing_4R->N
        L3: Root_1R!H-inRing_N-4R->N
            L4: Root_1R!H-inRing_N-4R->N_2R!H->O
                L5: Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing
                    L6: Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing_Ext-3R!H-R_5R!H->C
                        L7: Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing_Ext-3R!H-R_5R!H->C_Ext-1R!H-R
                    L6: Root_1R!H-inRing_N-4R->N_2R!H->O_3R!H-inRing_Ext-3R!H-R_N-5R!H->C
                L5: Root_1R!H-inRing_N-4R->N_2R!H->O_N-3R!H-inRing
            L4: Root_1R!H-inRing_N-4R->N_N-2R!H->O
                L5: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R
                    L6: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN
                        L7: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_3R!H->C
                            L8: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_3R!H->C_Ext-5R!H-R_Ext-5R!H-R
                        L7: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C
                            L8: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_2CN->C
                            L8: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_N-2CN->C
                                L9: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_N-2CN->C_Ext-5R!H-R_Ext-6R!H-R_Ext-6R!H-R_Ext-6R!H-R
                                L9: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_Sp-5R!H-2CN_N-3R!H->C_N-2CN->C_Ext-1R!H-R
                    L6: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-2CN-R_N-Sp-5R!H-2CN
                L5: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C
                    L6: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C_Ext-1R!H-R
                        L7: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C_Ext-1R!H-R_3R!H->O
                        L7: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_5R!H->C_Ext-1R!H-R_N-3R!H->O
                L5: Root_1R!H-inRing_N-4R->N_N-2R!H->O_Ext-4CH-R_N-5R!H->C
    L2: Root_N-1R!H-inRing
        L3: Root_N-1R!H-inRing_2R!H->C
            L4: Root_N-1R!H-inRing_2R!H->C_4R->C
            L4: Root_N-1R!H-inRing_2R!H->C_N-4R->C
                L5: Root_N-1R!H-inRing_2R!H->C_N-4R->C_Ext-1R!H-R
        L3: Root_N-1R!H-inRing_N-2R!H->C
            L4: Root_N-1R!H-inRing_N-2R!H->C_3R!H->C
                L5: Root_N-1R!H-inRing_N-2R!H->C_3R!H->C_4R->C
                L5: Root_N-1R!H-inRing_N-2R!H->C_3R!H->C_N-4R->C
                    L6: Root_N-1R!H-inRing_N-2R!H->C_3R!H->C_N-4R->C_Ext-1R!H-R
            L4: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C
                L5: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N
                    L6: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_4R->N
                    L6: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N
                        L7: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_5R!H->O
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_5R!H->O_Ext-4C-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_5R!H->O_Ext-1R!H-R
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_3NOS->O
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_3NOS->O_5BrCClFINPSSi->C
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_3NOS->O_N-5BrCClFINPSSi->C
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O_5BrCClFINPSSi->C
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O_5BrCClFINPSSi->C_Ext-1R!H-R
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_2N-inRing_N-3NOS->O_N-5BrCClFINPSSi->C
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_4CH->C_Ext-4C-R_N-5R!H->O_N-2N-inRing
                        L7: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-1R!H-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-5R!H-R_Ext-5R!H-R
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-5R!H-R_Ext-5R!H-R_3NOS->O
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_Ext-5R!H-R_Ext-5R!H-R_N-3NOS->O
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_3NOS->O
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_3NOS->O_Ext-5R!H-R_6R!H->N
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_3NOS->O_Ext-5R!H-R_N-6R!H->N
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-2N-R_N-3NOS->O
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-5R!H-R
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-5R!H-R_5R!H->C
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-5R!H-R_N-5R!H->C
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_7R!H->N
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_7R!H->N_5R!H->O
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_7R!H->N_N-5R!H->O
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_Sp-6R!H-5R!H_Ext-6R!H-R_N-7R!H->N
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-1R!H-R_Ext-5R!H-R_N-Sp-6R!H-5R!H
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_2NOS->N_N-4R->N_N-4CH->C_Ext-3NOS-R_Ext-5R!H-R_Ext-5R!H-R
                L5: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N
                    L6: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_3NOS->S
                        L7: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_3NOS->S_Ext-1R!H-R
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_3NOS->S_Ext-1R!H-R_Ext-5R!H-R
                    L6: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S
                        L7: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_Ext-3NO-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_4R->C
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C
                                        L11: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_7R!H->N
                                            L12: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_N-7R!H->N
                                                L13: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_N-7R!H->N_5N-inRing
                                                L13: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_5R!H->N_N-4R->C_Ext-5N-R_Ext-6R!H-R_N-7R!H->N_N-5N-inRing
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N_Ext-5CO-R_Ext-5CO-R
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N_5CO->O
                                    L10: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-1R!H-R_N-5R!H->N_N-5CO->O
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R_Ext-5R!H-R_Ext-5R!H-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R_Ext-5R!H-R_6R!H->N
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-3NO-R_Ext-5R!H-R_N-6R!H->N
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-4R-R_5R!H->O
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-4R-R_5R!H->O_Ext-4R-R
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_2OS->O_Ext-4R-R_N-5R!H->O
                        L7: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_N-2OS->O
                            L8: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_N-2OS->O_Ext-1R!H-R
                                L9: Root_N-1R!H-inRing_N-2R!H->C_N-3R!H->C_N-2NOS->N_N-3NOS->S_N-2OS->O_Ext-1R!H-R_Ext-5R!H-R
"""
)

