#!/usr/bin/env python
# encoding: utf-8

name = "concerted_intra_H_alphaQOOH_break/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["QCHO_OH"], ownReverse=False)

reverse = "OH+QCHO"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['LOSE_RADICAL', '*1', '1'],
    ['BREAK_BOND', '*4', 1, '*5'],
    ['CHANGE_BOND', '*4', 1, '*2'],
    ['GAIN_RADICAL', '*5', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *4 O   u0 {2,S} {3,S}
2 *2 R!H u0 {1,S} {4,S}
3 *5 O   u0 {1,S} {5,S}
4 *3 H   u0 {2,S}
5    H   u0 {3,S}
6 *1 R!H u1
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R",
    group = 
"""
1 *4 O   u0 {2,S} {3,S}
2 *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3 *5 O   u0 {1,S} {5,S}
4 *3 H   u0 {2,S}
5    H   u0 {3,S}
6 *1 R!H u1
7    R!H ux {2,[S,D,T,B,Q]}
8    C   ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_7R!H->O",
    group = 
"""
1 *4 O u0 {2,S} {3,S}
2 *2 C u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,S}
3 *5 O u0 {1,S} {5,S}
4 *3 H u0 {2,S}
5    H u0 {3,S}
6 *1 O u1
7    O ux {2,[S,D,T,B,Q]}
8    C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_7R!H->O_Ext-8R!H-R_Ext-9R!H-R",
    group = 
"""
1  *4 O   u0 r0 {2,S} {3,S}
2  *2 C   u0 r0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,S}
3  *5 O   u0 r0 {1,S} {5,S}
4  *3 H   u0 r0 {2,S}
5     H   u0 r0 {3,S}
6  *1 O   u1 r0
7     O   ux {2,[S,D,T,B,Q]}
8     C   u0 r0 {2,S} {9,S}
9     C   u0 r0 {8,S} {10,[S,D,T,B,Q]}
10    R!H ux {9,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O",
    group = 
"""
1 *4 O   u0 {2,S} {3,S}
2 *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3 *5 O   u0 {1,S} {5,S}
4 *3 H   u0 {2,S}
5    H   u0 {3,S}
6 *1 R!H u1
7    C   ux {2,[S,D,T,B,Q]}
8    C   ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-8R!H-R",
    group = 
"""
1  *4 O   u0 r0 {2,S} {3,S}
2  *2 C   u0 r0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,S}
3  *5 O   u0 r0 {1,S} {5,S}
4  *3 H   u0 r0 {2,S}
5     H   u0 r0 {3,S}
6  *1 O   u1 r0
7     C   ux {2,[S,D,T,B,Q]}
8     C   u0 r0 {2,S} {9,[S,D,T,B,Q]} {10,[S,D,T,B,Q]}
9     R!H ux {8,[S,D,T,B,Q]}
10    R!H ux {8,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 R!H u1 {10,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]}
8     C   ux {2,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C   ux {8,[S,D,T,B,Q]}
10    O   ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-10R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 R!H u1 {10,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]}
8     C   ux {2,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C   ux {8,[S,D,T,B,Q]}
10    O   ux {6,[S,D,T,B,Q]} {11,[S,D,T,B,Q]}
11    R!H ux {10,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-10R!H-R_Ext-9R!H-R",
    group = 
"""
1  *4 O   u0 r0 {2,S} {3,S}
2  *2 C   u0 r0 {1,S} {4,S} {7,S} {8,S}
3  *5 O   u0 r0 {1,S} {5,S}
4  *3 H   u0 r0 {2,S}
5     H   u0 r0 {3,S}
6  *1 R!H u1 {10,[S,D,T,B,Q]}
7     C   u0 r0 {2,S}
8     C   u0 r0 {2,S} {9,S}
9     C   u0 r0 {8,S} {12,[S,D,T,B,Q]}
10    O   ux {6,[S,D,T,B,Q]} {11,[S,D,T,B,Q]}
11    R!H ux {10,[S,D,T,B,Q]}
12    R!H ux {9,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-10R!H-R_Ext-11R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 O   u1 {10,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]}
8     C   ux {2,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C   ux {8,[S,D,T,B,Q]}
10    O   ux {6,[S,D,T,B,Q]} {11,[S,D,T,B,Q]}
11    C   ux {10,[S,D,T,B,Q]} {12,[S,D,T,B,Q]}
12    R!H ux {11,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-9R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 O   u1 {10,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]}
8     C   ux {2,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C   ux {8,[S,D,T,B,Q]} {11,[S,D,T,B,Q]}
10    O   ux {6,[S,D,T,B,Q]}
11    R!H ux {9,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-7R!H-R",
    group = 
"""
1 *4 O   u0 {2,S} {3,S}
2 *2 C   u0 {1,S} {4,S} {7,S}
3 *5 O   u0 {1,S} {5,S}
4 *3 H   u0 {2,S}
5    H   u0 {3,S}
6 *1 O   u1
7    C   u0 {2,S} {8,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
8    R!H ux {7,[S,D,T,B,Q]}
9    R!H ux {7,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R",
    group = 
"""
1  *4 O   u0 r0 {2,S} {3,S}
2  *2 C   u0 r0 {1,S} {4,S} {7,S}
3  *5 O   u0 r0 {1,S} {5,S}
4  *3 H   u0 r0 {2,S}
5     H   u0 r0 {3,S}
6  *1 O   u1 r0 {10,[S,D,T,B,Q]}
7     C   u0 r0 {2,S} {8,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
8     R!H ux {7,[S,D,T,B,Q]}
9     R!H ux {7,[S,D,T,B,Q]}
10    R!H ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R",
    group = 
"""
1 *4 O   u0 {2,S} {3,S}
2 *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3 *5 O   u0 {1,S} {5,S}
4 *3 H   u0 {2,S}
5    H   u0 {3,S}
6 *1 R!H u1 {9,[S,D,T,B,Q]}
7    C   ux {2,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8    C   ux {7,[S,D,T,B,Q]}
9    O   ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-9R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 R!H u1 {9,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8     C   ux {7,[S,D,T,B,Q]}
9     O   ux {6,[S,D,T,B,Q]} {10,[S,D,T,B,Q]}
10    R!H ux {9,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-9R!H-R_Ext-8R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 R!H u1 {9,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]} {8,S}
8     C   u0 r0 {7,S} {11,[S,D,T,B,Q]}
9     O   ux {6,[S,D,T,B,Q]} {10,[S,D,T,B,Q]}
10    R!H ux {9,[S,D,T,B,Q]}
11    R!H ux {8,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-9R!H-R_Ext-10R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 O   u1 {9,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8     C   ux {7,[S,D,T,B,Q]}
9     O   ux {6,[S,D,T,B,Q]} {10,[S,D,T,B,Q]}
10    C   ux {9,[S,D,T,B,Q]} {11,[S,D,T,B,Q]}
11    R!H ux {10,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-8R!H-R",
    group = 
"""
1  *4 O   u0 {2,S} {3,S}
2  *2 C   u0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3  *5 O   u0 {1,S} {5,S}
4  *3 H   u0 {2,S}
5     H   u0 {3,S}
6  *1 O   u1 {9,[S,D,T,B,Q]}
7     C   ux {2,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8     C   ux {7,[S,D,T,B,Q]} {10,[S,D,T,B,Q]}
9     O   ux {6,[S,D,T,B,Q]}
10    R!H ux {8,[S,D,T,B,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R
        L3: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_7R!H->O
            L4: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_7R!H->O_Ext-8R!H-R_Ext-9R!H-R
        L3: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O
            L4: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-8R!H-R
            L4: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R
                L5: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-10R!H-R
                    L6: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-10R!H-R_Ext-9R!H-R
                    L6: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-10R!H-R_Ext-11R!H-R
                L5: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-2R!H-R_N-7R!H->O_Ext-8R!H-R_Ext-6R!H-R_Ext-9R!H-R
    L2: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-7R!H-R
        L3: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R
    L2: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R
        L3: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-9R!H-R
            L4: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-9R!H-R_Ext-8R!H-R
            L4: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-9R!H-R_Ext-10R!H-R
        L3: Root_Ext-6R!H-R_Ext-7R!H-R_Ext-7R!H-R_Ext-6R!H-R_Ext-8R!H-R
"""
)

forbidden(
    label = "H_mig_7_membered_ring_3_4",
    group = 
"""
1    R!H u0 {2,S} {7,S}
2    R!H u0 {1,S} {3,S}
3 *2 R!H u0 {2,S} {4,S} {9,S}
4    R!H u0 {3,S} {5,S}
5    R!H u0 {4,S} {6,S}
6    R!H u0 {5,S} {7,S}
7    R!H u0 {1,S} {6,S} {8,S}
8 *1 R!H u1 {7,S}
9 *3 H   u0 {3,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_1_position_of_sidechain_res1",
    group = 
"""
1 *1 R!H u1 {2,[S,D,T]}
2    Cb  u0 {1,[S,D,T]} {3,B} {4,B}
3    Cb  u0 {2,B} {6,B}
4    Cb  u0 {2,B} {7,B}
5    Cb  u0 {6,B} {7,B}
6    Cb  u0 {3,B} {5,B}
7 *2 Cb  u0 {4,B} {5,B} {8,S}
8 *3 H   u0 {7,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 1 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 1.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_1_position_of_sidechain_res2",
    group = 
"""
1    C   u0 {3,S} {4,D} {7,[S,D,T]}
2 *2 C   u0 {3,D} {5,S} {8,S}
3    C   u0 {1,S} {2,D}
4    C   u0 {1,D} {6,S}
5    C   u0 {2,S} {6,D}
6    C   u0 {4,S} {5,D}
7 *1 R!H u1 {1,[S,D,T]}
8 *3 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 1 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 2.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_1_position_of_sidechain_res3",
    group = 
"""
1    C   u0 {3,D} {4,S} {7,[S,D,T]}
2 *2 C   u0 {3,S} {5,D} {8,S}
3    C   u0 {1,D} {2,S}
4    C   u0 {1,S} {6,D}
5    C   u0 {2,D} {6,S}
6    C   u0 {4,D} {5,S}
7 *1 R!H u1 {1,[S,D,T]}
8 *3 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 1 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 3.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_2_position_of_sidechain_res1",
    group = 
"""
1    R!H u0 {2,[S,D,T]} {3,[S,D,T]}
2    Cb  u0 {1,[S,D,T]} {4,B} {5,B}
3 *1 R!H u1 {1,[S,D,T]}
4    Cb  u0 {2,B} {7,B}
5    Cb  u0 {2,B} {8,B}
6    Cb  u0 {7,B} {8,B}
7 *2 Cb  u0 {4,B} {6,B} {9,S}
8    Cb  u0 {5,B} {6,B}
9 *3 H   u0 {7,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 1.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_2_position_of_sidechain_res2",
    group = 
"""
1    C   u0 {3,D} {4,S} {7,[S,D,T]}
2 *2 C   u0 {3,S} {5,D} {8,S}
3    C   u0 {1,D} {2,S}
4    C   u0 {1,S} {6,D}
5    C   u0 {2,D} {6,S}
6    C   u0 {4,D} {5,S}
7    R!H u0 {1,[S,D,T]} {9,[S,D,T]}
8 *3 H   u0 {2,S}
9 *1 R!H u1 {7,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 2.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_2_position_of_sidechain_res3",
    group = 
"""
1    C   u0 {3,S} {4,D} {7,[S,D,T]}
2 *2 C   u0 {3,D} {5,S} {8,S}
3    C   u0 {1,S} {2,D}
4    C   u0 {1,D} {6,S}
5    C   u0 {2,S} {6,D}
6    C   u0 {4,S} {5,D}
7    R!H u0 {1,[S,D,T]} {9,[S,D,T]}
8 *3 H   u0 {2,S}
9 *1 R!H u1 {7,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 3.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_3_position_of_sidechain_res1",
    group = 
"""
1     R!H u0 {2,[S,D,T]} {3,[S,D,T]}
2     Cb  u0 {1,[S,D,T]} {4,B} {5,B}
3     R!H u0 {1,[S,D,T]} {10,[S,D,T]}
4     Cb  u0 {2,B} {7,B}
5     Cb  u0 {2,B} {8,B}
6     Cb  u0 {7,B} {8,B}
7  *2 Cb  u0 {4,B} {6,B} {9,S}
8     Cb  u0 {5,B} {6,B}
9  *3 H   u0 {7,S}
10 *1 R!H u1 {3,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 1.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_3_position_of_sidechain_res2",
    group = 
"""
1     C   u0 {3,S} {4,D} {5,[S,D,T]}
2  *2 C   u0 {3,D} {6,S} {9,S}
3     C   u0 {1,S} {2,D}
4     C   u0 {1,D} {7,S}
5     R!H u0 {1,[S,D,T]} {8,[S,D,T]}
6     C   u0 {2,S} {7,D}
7     C   u0 {4,S} {6,D}
8     R!H u0 {5,[S,D,T]} {10,[S,D,T]}
9  *3 H   u0 {2,S}
10 *1 R!H u1 {8,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 2.
""",
)

forbidden(
    label = "H_mig_from_m_position_of_phenyl_sidegroup_to_3_position_of_sidechain_res3",
    group = 
"""
1     C   u0 {3,D} {4,S} {5,[S,D,T]}
2  *2 C   u0 {3,S} {6,D} {9,S}
3     C   u0 {1,D} {2,S}
4     C   u0 {1,S} {7,D}
5     R!H u0 {1,[S,D,T]} {8,[S,D,T]}
6     C   u0 {2,D} {7,S}
7     C   u0 {4,D} {6,S}
8     R!H u0 {5,[S,D,T]} {10,[S,D,T]}
9  *3 H   u0 {2,S}
10 *1 R!H u1 {8,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the meta-position
because the TS would be far too strained. Resonance form 3.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_cyc6_sidegroup_to_1_position_of_double_bonded_sidechain_dir_1",
    group = 
"""
1    R!H u0 {3,[S,D,T,B]} {4,[S,D,T,B]} {7,D}
2 *2 R!H u0 {5,[S,D,T,B]} {6,[S,D,T,B]} {8,S}
3    R!H u0 {1,[S,D,T,B]} {5,[S,D,T,B]}
4    R!H u0 {1,[S,D,T,B]} {6,[S,D,T,B]}
5    R!H u0 {2,[S,D,T,B]} {3,[S,D,T,B]}
6    R!H u0 {2,[S,D,T,B]} {4,[S,D,T,B]}
7 *1 R!H u1 {1,D}
8 *3 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical double-bonded to a 6-membered ring from abstracting an H the para position
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_1_position_of_sidechain_res1",
    group = 
"""
1 *1 R!H u1 {2,[S,D,T]}
2    Cb  u0 {1,[S,D,T]} {3,B} {4,B}
3    Cb  u0 {2,B} {6,B}
4    Cb  u0 {2,B} {7,B}
5 *2 Cb  u0 {6,B} {7,B} {8,S}
6    Cb  u0 {3,B} {5,B}
7    Cb  u0 {4,B} {5,B}
8 *3 H   u0 {5,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 1 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 1.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_1_position_of_sidechain_res2",
    group = 
"""
1    C   u0 {3,D} {4,S} {7,[S,D,T]}
2 *2 C   u0 {5,D} {6,S} {8,S}
3    C   u0 {1,D} {5,S}
4    C   u0 {1,S} {6,D}
5    C   u0 {2,D} {3,S}
6    C   u0 {2,S} {4,D}
7 *1 R!H u1 {1,[S,D,T]}
8 *3 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 1 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 2.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_1_position_of_sidechain_res3",
    group = 
"""
1    C   u0 {3,S} {4,D} {7,[S,D,T]}
2 *2 C   u0 {5,S} {6,D} {8,S}
3    C   u0 {1,S} {5,D}
4    C   u0 {1,D} {6,S}
5    C   u0 {2,S} {3,D}
6    C   u0 {2,D} {4,S}
7 *1 R!H u1 {1,[S,D,T]}
8 *3 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 1 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 3.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_2_position_of_sidechain_res1",
    group = 
"""
1    R!H u0 {2,[S,D,T]} {3,[S,D,T]}
2    Cb  u0 {1,[S,D,T]} {4,B} {5,B}
3 *1 R!H u1 {1,[S,D,T]}
4    Cb  u0 {2,B} {7,B}
5    Cb  u0 {2,B} {8,B}
6 *2 Cb  u0 {7,B} {8,B} {9,S}
7    Cb  u0 {4,B} {6,B}
8    Cb  u0 {5,B} {6,B}
9 *3 H   u0 {6,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 1.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_2_position_of_sidechain_res2",
    group = 
"""
1    C   u0 {3,D} {4,S} {7,[S,D,T]}
2 *2 C   u0 {5,D} {6,S} {8,S}
3    C   u0 {1,D} {5,S}
4    C   u0 {1,S} {6,D}
5    C   u0 {2,D} {3,S}
6    C   u0 {2,S} {4,D}
7    R!H u0 {1,[S,D,T]} {9,[S,D,T]}
8 *3 H   u0 {2,S}
9 *1 R!H u1 {7,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 2.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_2_position_of_sidechain_res3",
    group = 
"""
1    C   u0 {3,S} {4,D} {7,[S,D,T]}
2 *2 C   u0 {5,S} {6,D} {8,S}
3    C   u0 {1,S} {5,D}
4    C   u0 {1,D} {6,S}
5    C   u0 {2,S} {3,D}
6    C   u0 {2,D} {4,S}
7    R!H u0 {1,[S,D,T]} {9,[S,D,T]}
8 *3 H   u0 {2,S}
9 *1 R!H u1 {7,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 3.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_3_position_of_sidechain_res1",
    group = 
"""
1     R!H u0 {2,[S,D,T]} {3,[S,D,T]}
2     Cb  u0 {1,[S,D,T]} {4,B} {5,B}
3     R!H u0 {1,[S,D,T]} {10,[S,D,T]}
4     Cb  u0 {2,B} {7,B}
5     Cb  u0 {2,B} {8,B}
6  *2 Cb  u0 {7,B} {8,B} {9,S}
7     Cb  u0 {4,B} {6,B}
8     Cb  u0 {5,B} {6,B}
9  *3 H   u0 {6,S}
10 *1 R!H u1 {3,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 1.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_3_position_of_sidechain_res2",
    group = 
"""
1     C   u0 {3,S} {4,D} {7,[S,D,T]}
2  *2 C   u0 {5,S} {6,D} {9,S}
3     C   u0 {1,S} {5,D}
4     C   u0 {1,D} {6,S}
5     C   u0 {2,S} {3,D}
6     C   u0 {2,D} {4,S}
7     R!H u0 {1,[S,D,T]} {8,[S,D,T]}
8     R!H u0 {7,[S,D,T]} {10,[S,D,T]}
9  *3 H   u0 {2,S}
10 *1 R!H u1 {8,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 2.
""",
)

forbidden(
    label = "H_mig_from_p_position_of_phenyl_sidegroup_to_3_position_of_sidechain_res3",
    group = 
"""
1     C   u0 {3,D} {4,S} {7,[S,D,T]}
2  *2 C   u0 {5,D} {6,S} {9,S}
3     C   u0 {1,D} {5,S}
4     C   u0 {1,S} {6,D}
5     C   u0 {2,D} {3,S}
6     C   u0 {2,S} {4,D}
7     R!H u0 {1,[S,D,T]} {8,[S,D,T]}
8     R!H u0 {7,[S,D,T]} {10,[S,D,T]}
9  *3 H   u0 {2,S}
10 *1 R!H u1 {8,[S,D,T]}
""",
    shortDesc = """""",
    longDesc = 
"""
Forbid a radical 2 atoms away from a phenyl side group from abstracting an H from the para-position
because the TS would be far too strained. Resonance form 3.
""",
)

forbidden(
    label = "fulvene_H_mig_ring_edge_to_tail",
    group = 
"""
1    C u0 {3,D} {4,S} {6,S}
2 *2 C u0 {3,S} {5,S} {7,S}
3    C u0 {1,D} {2,S}
4    C u0 {1,S} {5,D}
5    C u0 {2,S} {4,D}
6 *1 C u1 {1,S}
7 *3 H u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Prevents the fulvene + H radical with radical site on the tail from abstracting an H
from the far edge of the ring
""",
)

forbidden(
    label = "fulvene_H_mig_tail_to_ring_edge",
    group = 
"""
1 *2 C u1 {2,S} {7,S}
2    C u0 {1,S} {3,D} {4,S}
3    C u0 {2,D} {5,S}
4    C u0 {2,S} {6,D}
5 *1 C u0 {3,S} {6,S}
6    C u0 {4,D} {5,S}
7 *3 H u0 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""
Prevents the fulvene + H radical with radical site on the ring-edge from abstracting an H
from the end of the tail
""",
)

