# For conda build
package:
  name: rmgdatabase
  version: 3.3.0

source:
  path: ../

build:
  noarch: generic
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-database
  license: MIT
  summary: "Database for RMG: a program for automatically generating kinetic models of chemical reaction mechanisms."
