#!/usr/bin/env python
# encoding: utf-8

name = "Enol_Ether_Formation/groups"
shortDesc = ""
longDesc = """
*4F
                                      |
C - *1O - *2C - *3C - *4F <=>  *1O - *2C = *3C

or with resonance

                                    *4F
                                    |
*1O+ = *2C- - *3C - *4F <=>  *1O - *2C = *3C
"""

template(reactants=["Root"], products=["perfluorinated_alkene"], ownReverse=False)

reverse = "Enol_Ether_Transformation"
reversible = True

reactantNum = 1

productNum = 1

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*2', 1, '*4'],
    ['CHANGE_BOND', '*3', 1, '*2'],
    ['LOSE_PAIR', '*2', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C       u0 p1 {2,S} {3,S}
2 *1 O       u0 p2 {1,S} {5,S}
3 *3 C       u0 p0 {1,S} {4,S}
4 *4 [F1s,H] u0 {3,S}
5    C       u0 p0 c0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-3C-R",
    group = 
"""
1 *2 C   u0 p1 {2,S} {3,S}
2 *1 O   u0 p2 {1,S} {5,S}
3 *3 C   u0 p0 {1,S} {4,S} {6,[S,B,D,T,Q]}
4 *4 F1s u0 {3,S}
5    C   u0 p0 c0 {2,S}
6    F   ux {3,[S,B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-3C-R_Ext-5C-R_7R!H->C",
    group = 
"""
1 *2 C   u0 p1 {2,S} {3,S}
2 *1 O   u0 p2 {1,S} {5,S}
3 *3 C   u0 p0 {1,S} {4,S} {6,[S,B,D,T,Q]}
4 *4 F1s u0 {3,S}
5    C   u0 p0 c0 {2,S} {7,S}
6    F   ux {3,[S,B,D,T,Q]}
7    C   u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-3C-R_Ext-5C-R_7R!H->C_Ext-7C-R_8R!H->C",
    group = 
"""
1 *2 C   u0 p1 r0 {2,S} {3,S}
2 *1 O   u0 p2 r0 {1,S} {5,S}
3 *3 C   u0 p0 r0 {1,S} {4,S} {6,[S,B,D,T,Q]}
4 *4 F1s u0 r0 {3,S}
5    C   u0 p0 c0 r0 {2,S} {7,S}
6    F   ux {3,[S,B,D,T,Q]}
7    C   u0 r0 {5,S} {8,S}
8    C   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-3C-R_Ext-5C-R_7R!H->C_Ext-7C-R_N-8R!H->C",
    group = 
"""
1 *2 C   u0 p1 r0 {2,S} {3,S}
2 *1 O   u0 p2 r0 {1,S} {5,S}
3 *3 C   u0 p0 r0 {1,S} {4,S} {6,[S,B,D,T,Q]}
4 *4 F1s u0 r0 {3,S}
5    C   u0 p0 c0 r0 {2,S} {7,S}
6    F   ux {3,[S,B,D,T,Q]}
7    C   u0 r0 {5,S} {8,S}
8    F   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-3C-R_Ext-5C-R_N-7R!H->C",
    group = 
"""
1 *2 C   u0 p1 r0 {2,S} {3,S}
2 *1 O   u0 p2 r0 {1,S} {5,S}
3 *3 C   u0 p0 r0 {1,S} {4,S} {6,[S,B,D,T,Q]}
4 *4 F1s u0 r0 {3,S}
5    C   u0 p0 c0 r0 {2,S} {7,S}
6    F   ux {3,[S,B,D,T,Q]}
7    F   u0 r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-5C-R",
    group = 
"""
1 *2 C   u0 p1 {2,S} {3,S}
2 *1 O   u0 p2 {1,S} {5,S}
3 *3 C   u0 p0 {1,S} {4,S}
4 *4 H   u0 {3,S}
5    C   u0 p0 c0 {2,S} {6,[S,B,D,T,Q]}
6    R!H ux {5,[S,B,D,T,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-3C-R
        L3: Root_Ext-3C-R_Ext-5C-R_7R!H->C
            L4: Root_Ext-3C-R_Ext-5C-R_7R!H->C_Ext-7C-R_8R!H->C
            L4: Root_Ext-3C-R_Ext-5C-R_7R!H->C_Ext-7C-R_N-8R!H->C
        L3: Root_Ext-3C-R_Ext-5C-R_N-7R!H->C
    L2: Root_Ext-5C-R
"""
)

