#!/usr/bin/env python
# encoding: utf-8

name = "CH2F2"
shortDesc = "/Users/rwest/Code/Importer/RMG-models/CH2F2/hfcmech_v448a.txt"
longDesc = """
b'Valeri I. Babushok, Michael J. Hegetschweiler, Gregory T. Linteris, Donald R. Burgess, Jr., Jeffrey A. Manion, Robert R. Burrell, Michael J. Hegetschweiler\nObtained via email from Donald R. Burgess, Jr.\nModel for HFC combustion of refrigerants R32, R152a, R134a, R125, and R116'
"""
autoGenerated=False
entry(
    index = 0,
    label = "O2 + H <=> OH + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.65e+16,'cm^3/(mol*s)'), n=-0.67, Ea=(17041,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + H <=> OH + O""",
)

entry(
    index = 1,
    label = "H2 + O <=> OH + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(38700,'cm^3/(mol*s)'), n=2.7, Ea=(6260,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2 + O <=> OH + H""",
)

entry(
    index = 2,
    label = "H2 + OH <=> H2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.16e+08,'cm^3/(mol*s)'), n=1.51, Ea=(3430,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2 + OH <=> H2O + H""",
)

entry(
    index = 3,
    label = "OH + OH <=> H2O + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(35700,'cm^3/(mol*s)'), n=2.4, Ea=(-2110,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is OH + OH <=> H2O + O""",
)

entry(
    index = 4,
    label = "O2 + H <=> HO2",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(5.12e+12,'cm^3/(mol*s)'), n=0.44, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.33e+19,'cm^6/(mol^2*s)'), n=-1.4, Ea=(0,'cal/mol'), T0=(1,'K')), alpha=0.5, T3=(1e-30,'K'), T1=(1e+30,'K'), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 11.89, 'O=C=O': 2.18, '[C-]#[O+]': 1.09, '[O][O]': 0.85}),
    shortDesc = """The chemkin file reaction is O2 + H <=> HO2""",
)

entry(
    index = 5,
    label = "OH + H <=> H2O",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(2.2e+22,'cm^6/(mol^2*s)'), n=-2, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 3.65, '[H][H]': 0.73}),
    shortDesc = """The chemkin file reaction is OH + H <=> H2O""",
)

entry(
    index = 6,
    label = "H + H <=> H2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1e+18,'cm^6/(mol^2*s)'), n=-1, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'O': 0.0, 'O=C=O': 0.0, '[H][H]': 0.0}),
    shortDesc = """The chemkin file reaction is H + H <=> H2""",
)

entry(
    index = 7,
    label = "H + H + H2 <=> H2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9e+16,'cm^6/(mol^2*s)'), n=-0.6, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + H + H2 <=> H2 + H2""",
)

entry(
    index = 8,
    label = "H + H + H2O <=> H2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+19,'cm^6/(mol^2*s)'), n=-1.25, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + H + H2O <=> H2 + H2O""",
)

entry(
    index = 9,
    label = "H + H + CO2 <=> H2 + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.5e+20,'cm^6/(mol^2*s)'), n=-2, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + H + CO2 <=> H2 + CO2""",
)

entry(
    index = 10,
    label = "H2O2 + H <=> H2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+07,'cm^3/(mol*s)'), n=2, Ea=(5200,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + H <=> H2 + HO2""",
)

entry(
    index = 11,
    label = "H2O2 + H <=> H2O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(3600,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + H <=> H2O + OH""",
)

entry(
    index = 12,
    label = "O + O <=> O2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.2e+17,'cm^6/(mol^2*s)'), n=-1, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'O': 15.4, 'O=C=O': 3.6, '[C-]#[O+]': 1.75, '[H][H]': 2.4}),
    shortDesc = """The chemkin file reaction is O + O <=> O2""",
)

entry(
    index = 13,
    label = "O + H <=> OH",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(5e+17,'cm^6/(mol^2*s)'), n=-1, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is O + H <=> OH""",
)

entry(
    index = 14,
    label = "HO2 + H <=> H2O + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.97e+12,'cm^3/(mol*s)'), n=0, Ea=(671,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + H <=> H2O + O""",
)

entry(
    index = 15,
    label = "HO2 + H <=> O2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.48e+13,'cm^3/(mol*s)'), n=0, Ea=(1068,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + H <=> O2 + H2""",
)

entry(
    index = 16,
    label = "HO2 + H <=> OH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.4e+13,'cm^3/(mol*s)'), n=0, Ea=(635,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + H <=> OH + OH""",
)

entry(
    index = 17,
    label = "HO2 + O <=> O2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + O <=> O2 + OH""",
)

entry(
    index = 18,
    label = "H2O2 + O <=> HO2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.63e+06,'cm^3/(mol*s)'), n=2, Ea=(4000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + O <=> HO2 + OH""",
)

entry(
    index = 19,
    label = "HO2 + OH <=> O2 + H2O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(1.45e+13,'cm^3/(mol*s)'), n=0, Ea=(-500,'cal/mol'), T0=(1,'K')), Arrhenius(A=(5e+15,'cm^3/(mol*s)'), n=0, Ea=(17330,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is HO2 + OH <=> O2 + H2O""",
)

entry(
    index = 20,
    label = "HO2 + HO2 <=> O2 + H2O2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(1.3e+11,'cm^3/(mol*s)'), n=0, Ea=(-1630,'cal/mol'), T0=(1,'K')), Arrhenius(A=(4.2e+14,'cm^3/(mol*s)'), n=0, Ea=(12000,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is HO2 + HO2 <=> O2 + H2O2""",
)

entry(
    index = 21,
    label = "H2O2 + OH <=> H2O + HO2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(427,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.7e+18,'cm^3/(mol*s)'), n=0, Ea=(29410,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is H2O2 + OH <=> H2O + HO2""",
)

entry(
    index = 22,
    label = "OH + OH <=> H2O2",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(7.4e+13,'cm^3/(mol*s)'), n=-0.37, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.3e+18,'cm^6/(mol^2*s)'), n=-0.9, Ea=(-1700,'cal/mol'), T0=(1,'K')), alpha=0.7346, T3=(94,'K'), T1=(1756,'K'), T2=(5182,'K'), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is OH + OH <=> H2O2""",
)

entry(
    index = 23,
    label = "H2 + F <=> H + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.56e+12,'cm^3/(mol*s)'), n=0.5, Ea=(650,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2 + F <=> H + HF""",
)

entry(
    index = 24,
    label = "H2O + F <=> OH + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3e+09,'cm^3/(mol*s)'), n=1.5, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O + F <=> OH + HF""",
)

entry(
    index = 25,
    label = "OH + F <=> O + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is OH + F <=> O + HF""",
)

entry(
    index = 26,
    label = "HO2 + F <=> O2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+12,'cm^3/(mol*s)'), n=0.5, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + F <=> O2 + HF""",
)

entry(
    index = 27,
    label = "CH3 + H <=> CH4",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.39e+16,'cm^3/(mol*s)'), n=-0.53, Ea=(536,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.62e+33,'cm^6/(mol^2*s)'), n=-4.76, Ea=(2440,'cal/mol'), T0=(1,'K')), alpha=0.783, T3=(74,'K'), T1=(2941,'K'), T2=(6964,'K'), efficiencies={'C': 3.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH3 + H <=> CH4""",
)

entry(
    index = 28,
    label = "CH4 + H <=> CH3 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.6e+08,'cm^3/(mol*s)'), n=1.62, Ea=(10840,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + H <=> CH3 + H2""",
)

entry(
    index = 29,
    label = "CH4 + O <=> CH3 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.02e+09,'cm^3/(mol*s)'), n=1.5, Ea=(8600,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + O <=> CH3 + OH""",
)

entry(
    index = 30,
    label = "CH4 + OH <=> CH3 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+08,'cm^3/(mol*s)'), n=1.6, Ea=(3120,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + OH <=> CH3 + H2O""",
)

entry(
    index = 31,
    label = "CH3 + HO2 <=> CH4 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + HO2 <=> CH4 + O2""",
)

entry(
    index = 32,
    label = "CH2O + CH3 <=> HCO + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3320,'cm^3/(mol*s)'), n=2.81, Ea=(5860,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2O + CH3 <=> HCO + CH4""",
)

entry(
    index = 33,
    label = "HCO + CH3 <=> CO + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.65e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + CH3 <=> CO + CH4""",
)

entry(
    index = 34,
    label = "CH3 + O2 <=> CH2O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.31e+12,'cm^3/(mol*s)'), n=0, Ea=(20315,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + O2 <=> CH2O + OH""",
)

entry(
    index = 35,
    label = "CH3 + O <=> CH2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.06e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + O <=> CH2O + H""",
)

entry(
    index = 36,
    label = "CH3 + O => CO + H2 + H",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.37e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + O => CO + H2 + H""",
)

entry(
    index = 37,
    label = "CH3 + OH => CH2O + H2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(8e+09,'cm^3/(mol*s)'), n=0.5, Ea=(-1755,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + OH => CH2O + H2""",
)

entry(
    index = 38,
    label = "CH + O2 <=> HCO + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.71e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH + O2 <=> HCO + O""",
)

entry(
    index = 39,
    label = "CH + H2O <=> CH2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.71e+12,'cm^3/(mol*s)'), n=0, Ea=(-755,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH + H2O <=> CH2O + H""",
)

entry(
    index = 40,
    label = "CH + CO2 <=> CO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.9e+14,'cm^3/(mol*s)'), n=0, Ea=(15792,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH + CO2 <=> CO + HCO""",
)

entry(
    index = 41,
    label = "CH + O <=> CO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.7e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH + O <=> CO + H""",
)

entry(
    index = 42,
    label = "CH + OH <=> HCO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH + OH <=> HCO + H""",
)

entry(
    index = 43,
    label = "C2H2 + O <=> HCCO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.35e+07,'cm^3/(mol*s)'), n=2, Ea=(1900,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H2 + O <=> HCCO + H""",
)

entry(
    index = 44,
    label = "C2H2 + OH <=> CO + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000483,'cm^3/(mol*s)'), n=4, Ea=(-2000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H2 + OH <=> CO + CH3""",
)

entry(
    index = 45,
    label = "C2H2 + OH <=> CH2CO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000218,'cm^3/(mol*s)'), n=4.5, Ea=(-1000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H2 + OH <=> CH2CO + H""",
)

entry(
    index = 46,
    label = "CH2O + H <=> HCO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.74e+07,'cm^3/(mol*s)'), n=1.9, Ea=(2742,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2O + H <=> HCO + H2""",
)

entry(
    index = 47,
    label = "CH2O + O <=> HCO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.9e+13,'cm^3/(mol*s)'), n=0, Ea=(3540,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2O + O <=> HCO + OH""",
)

entry(
    index = 48,
    label = "CH2O + OH <=> HCO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.43e+09,'cm^3/(mol*s)'), n=1.18, Ea=(-447,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2O + OH <=> HCO + H2O""",
)

entry(
    index = 49,
    label = "CH2O + HO2 <=> HCO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.6e+06,'cm^3/(mol*s)'), n=2, Ea=(12000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2O + HO2 <=> HCO + H2O2""",
)

entry(
    index = 50,
    label = "CO + H2 <=> CH2O",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(4.3e+07,'cm^3/(mol*s)'), n=1.5, Ea=(79600,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5.07e+27,'cm^6/(mol^2*s)'), n=-3.42, Ea=(84350,'cal/mol'), T0=(1,'K')), alpha=0.932, T3=(197,'K'), T1=(1540,'K'), T2=(10300,'K'), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CO + H2 <=> CH2O""",
)

entry(
    index = 51,
    label = "CH2O + O2 <=> HCO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(40000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2O + O2 <=> HCO + HO2""",
)

entry(
    index = 52,
    label = "HCO + O2 <=> CO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.35e+13,'cm^3/(mol*s)'), n=0, Ea=(400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + O2 <=> CO + HO2""",
)

entry(
    index = 53,
    label = "HCO + H2O <=> CO + H + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+18,'cm^3/(mol*s)'), n=-1, Ea=(17000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + H2O <=> CO + H + H2O""",
)

entry(
    index = 54,
    label = "HCO <=> CO + H",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.87e+17,'cm^3/(mol*s)'), n=-1, Ea=(17000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 0.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is HCO <=> CO + H""",
)

entry(
    index = 55,
    label = "HCO + O <=> CO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + O <=> CO + OH""",
)

entry(
    index = 56,
    label = "HCO + O <=> CO2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + O <=> CO2 + H""",
)

entry(
    index = 57,
    label = "HCO + OH <=> CO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + OH <=> CO + H2O""",
)

entry(
    index = 58,
    label = "HCO + H <=> CO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.34e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCO + H <=> CO + H2""",
)

entry(
    index = 59,
    label = "HCO + H <=> CH2O",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.09e+12,'cm^3/(mol*s)'), n=0.48, Ea=(-260,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.47e+24,'cm^6/(mol^2*s)'), n=-2.57, Ea=(425,'cal/mol'), T0=(1,'K')), alpha=0.7824, T3=(271,'K'), T1=(275,'K'), T2=(6570,'K'), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is HCO + H <=> CH2O""",
)

entry(
    index = 60,
    label = "CO + OH <=> CO2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.76e+07,'cm^3/(mol*s)'), n=1.23, Ea=(70,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CO + OH <=> CO2 + H""",
)

entry(
    index = 61,
    label = "CO + HO2 <=> CO2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+14,'cm^3/(mol*s)'), n=0, Ea=(23600,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CO + HO2 <=> CO2 + OH""",
)

entry(
    index = 62,
    label = "CO + O2 <=> CO2 + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.5e+12,'cm^3/(mol*s)'), n=0, Ea=(47800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CO + O2 <=> CO2 + O""",
)

entry(
    index = 63,
    label = "CO + O <=> CO2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.8e+10,'cm^3/(mol*s)'), n=0, Ea=(2385,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.02e+14,'cm^6/(mol^2*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 3.5, '[C-]#[O+]': 1.5, '[H][H]': 2.0, '[O][O]': 6.0}),
    shortDesc = """The chemkin file reaction is CO + O <=> CO2""",
)

entry(
    index = 64,
    label = "CH3O + O2 <=> CH2O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.28e-13,'cm^3/(mol*s)'), n=7.6, Ea=(-3530,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3O + O2 <=> CH2O + HO2""",
)

entry(
    index = 65,
    label = "CH3O + H <=> CH3 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+12,'cm^3/(mol*s)'), n=0.5, Ea=(-110,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3O + H <=> CH3 + OH""",
)

entry(
    index = 66,
    label = "CH3O + H <=> CH2O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3O + H <=> CH2O + H2""",
)

entry(
    index = 67,
    label = "CH3 + O2 <=> CH3O + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.56e+13,'cm^3/(mol*s)'), n=0, Ea=(30480,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + O2 <=> CH3O + O""",
)

entry(
    index = 68,
    label = "CH3 + HO2 <=> CH3O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.78e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + HO2 <=> CH3O + OH""",
)

entry(
    index = 69,
    label = "CH2O + H <=> CH3O",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(5.4e+11,'cm^3/(mol*s)'), n=0.45, Ea=(2600,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.2e+30,'cm^6/(mol^2*s)'), n=-4.8, Ea=(5560,'cal/mol'), T0=(1,'K')), alpha=0.758, T3=(94,'K'), T1=(1555,'K'), T2=(4200,'K'), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2O + H <=> CH3O""",
)

entry(
    index = 70,
    label = "CH2CO + H <=> HCCO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+13,'cm^3/(mol*s)'), n=0, Ea=(8000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CO + H <=> HCCO + H2""",
)

entry(
    index = 71,
    label = "CH2CO + H <=> CO + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.13e+13,'cm^3/(mol*s)'), n=0, Ea=(3428,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CO + H <=> CO + CH3""",
)

entry(
    index = 72,
    label = "CH2CO + O <=> HCCO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(8000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CO + O <=> HCCO + OH""",
)

entry(
    index = 73,
    label = "CH2CO + OH <=> HCCO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.5e+12,'cm^3/(mol*s)'), n=0, Ea=(2000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CO + OH <=> HCCO + H2O""",
)

entry(
    index = 74,
    label = "HCCO + O2 <=> CO + CO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.2e+12,'cm^3/(mol*s)'), n=0, Ea=(854,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCCO + O2 <=> CO + CO + OH""",
)

entry(
    index = 75,
    label = "HCCO + O <=> CO + CO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCCO + O <=> CO + CO + H""",
)

entry(
    index = 76,
    label = "HCCO + HCCO <=> CO + CO + C2H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HCCO + HCCO <=> CO + CO + C2H2""",
)

entry(
    index = 77,
    label = "CH2CO + H <=> CH2CHO",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(4.87e+11,'cm^3/(mol*s)'), n=0.42, Ea=(-1755,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.01e+42,'cm^6/(mol^2*s)'), n=-7.63, Ea=(3854,'cal/mol'), T0=(1,'K')), alpha=0.465, T3=(201,'K'), T1=(1773,'K'), T2=(5333,'K'), efficiencies={'C': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2CO + H <=> CH2CHO""",
)

entry(
    index = 78,
    label = "CH2CHO + O2 <=> CH2O + CO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+10,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + O2 <=> CH2O + CO + OH""",
)

entry(
    index = 79,
    label = "CH2CHO + O2 => HCO + HCO + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(2.35e+10,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + O2 => HCO + HCO + OH""",
)

entry(
    index = 80,
    label = "CH2CHO + H <=> HCO + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + H <=> HCO + CH3""",
)

entry(
    index = 81,
    label = "CH2CHO + H <=> CH2CO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + H <=> CH2CO + H2""",
)

entry(
    index = 82,
    label = "CH2CHO + OH <=> CH2CO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + OH <=> CH2CO + H2O""",
)

entry(
    index = 83,
    label = "CH2F2 + H <=> CHF2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.49e+14,'cm^3/(mol*s)'), n=0, Ea=(14945,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F2 + H <=> CHF2 + H2""",
)

entry(
    index = 84,
    label = "CH2F2 + O <=> CHF2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.86e+14,'cm^3/(mol*s)'), n=0, Ea=(13461,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F2 + O <=> CHF2 + OH""",
)

entry(
    index = 85,
    label = "CH2F2 + OH <=> CHF2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68e+13,'cm^3/(mol*s)'), n=0, Ea=(7192,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F2 + OH <=> CHF2 + H2O""",
)

entry(
    index = 86,
    label = "CH2F2 + F <=> CHF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.13e+14,'cm^3/(mol*s)'), n=0, Ea=(4647,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F2 + F <=> CHF2 + HF""",
)

entry(
    index = 87,
    label = "CH2F2 <=> CHF + HF",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.25e+15,'s^-1'), n=0, Ea=(81800,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(9.8e+17,'cm^3/(mol*s)'), n=0, Ea=(62600,'cal/mol'), T0=(1,'K')), alpha=0.08, T3=(1e-30,'K'), T1=(1e+30,'K'), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2F2 <=> CHF + HF""",
)

entry(
    index = 88,
    label = "CHF2 + O2 <=> CF2O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.46e+10,'cm^3/(mol*s)'), n=0, Ea=(3500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + O2 <=> CF2O + OH""",
)

entry(
    index = 89,
    label = "CHF2 + H <=> CHF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + H <=> CHF + HF""",
)

entry(
    index = 90,
    label = "CHF2 + O <=> CF2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.7e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + O <=> CF2O + H""",
)

entry(
    index = 91,
    label = "CHF2 + OH <=> CHFO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + OH <=> CHFO + HF""",
)

entry(
    index = 92,
    label = "CHF2 + F <=> CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + F <=> CF2 + HF""",
)

entry(
    index = 93,
    label = "CHF2 + HO2 <=> CH2F2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.26e+13,'cm^3/(mol*s)'), n=0, Ea=(4990,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + HO2 <=> CH2F2 + O2""",
)

entry(
    index = 94,
    label = "CHF + O2 <=> CHFO + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.37e+13,'cm^3/(mol*s)'), n=0, Ea=(7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + O2 <=> CHFO + O""",
)

entry(
    index = 95,
    label = "CHF + H2O <=> CH2O + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+12,'cm^3/(mol*s)'), n=0, Ea=(6500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + H2O <=> CH2O + HF""",
)

entry(
    index = 96,
    label = "CHF + H <=> CH + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.95e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + H <=> CH + HF""",
)

entry(
    index = 97,
    label = "CHF + O <=> CO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + O <=> CO + HF""",
)

entry(
    index = 98,
    label = "CHF + OH <=> CHFO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + OH <=> CHFO + H""",
)

entry(
    index = 99,
    label = "CHF + OH <=> HCO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + OH <=> HCO + HF""",
)

entry(
    index = 100,
    label = "CF2 + O2 <=> CF2O + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.67e+13,'cm^3/(mol*s)'), n=0, Ea=(26500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2 + O2 <=> CF2O + O""",
)

entry(
    index = 101,
    label = "CF2 + H2O <=> CHFO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+12,'cm^3/(mol*s)'), n=0, Ea=(25000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2 + H2O <=> CHFO + HF""",
)

entry(
    index = 102,
    label = "CF2 + O <=> CFO + F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2 + O <=> CFO + F""",
)

entry(
    index = 103,
    label = "CF2 + OH <=> CF2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.64e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2 + OH <=> CF2O + H""",
)

entry(
    index = 104,
    label = "CF2 + OH <=> CFO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2 + OH <=> CFO + HF""",
)

entry(
    index = 105,
    label = "CHFO <=> CO + HF",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(2.48e+25,'cm^3/(mol*s)'), n=-3, Ea=(43000,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """The chemkin file reaction is CHFO <=> CO + HF""",
)

entry(
    index = 106,
    label = "CHFO + H <=> CFO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+08,'cm^3/(mol*s)'), n=1.77, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFO + H <=> CFO + H2""",
)

entry(
    index = 107,
    label = "CHFO + O <=> CFO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9e+12,'cm^3/(mol*s)'), n=0, Ea=(3080,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFO + O <=> CFO + OH""",
)

entry(
    index = 108,
    label = "CHFO + OH <=> CFO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83e+13,'cm^3/(mol*s)'), n=0, Ea=(6620,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFO + OH <=> CFO + H2O""",
)

entry(
    index = 109,
    label = "CHFO + F <=> CFO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.65e+13,'cm^3/(mol*s)'), n=0, Ea=(1800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFO + F <=> CFO + HF""",
)

entry(
    index = 110,
    label = "CFO + F <=> CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFO + F <=> CF2O""",
)

entry(
    index = 111,
    label = "CF2O + H <=> CFO + HF",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(2.4e+07,'cm^3/(mol*s)'), n=1.88, Ea=(35900,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.2e+10,'cm^3/(mol*s)'), n=0.83, Ea=(22300,'cal/mol'), T0=(1,'K')), Arrhenius(A=(5.5e+08,'cm^3/(mol*s)'), n=1.42, Ea=(18900,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is CF2O + H <=> CFO + HF""",
)

entry(
    index = 112,
    label = "CO + F <=> CFO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3.09e+19,'cm^6/(mol^2*s)'), n=-1.4, Ea=(-487,'cal/mol'), T0=(1,'K')), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 18.0}),
    shortDesc = """The chemkin file reaction is CO + F <=> CFO""",
)

entry(
    index = 113,
    label = "CFO + O <=> CO2 + F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFO + O <=> CO2 + F""",
)

entry(
    index = 114,
    label = "CFO + OH <=> CO2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFO + OH <=> CO2 + HF""",
)

entry(
    index = 115,
    label = "CFO + H <=> CO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFO + H <=> CO + HF""",
)

entry(
    index = 116,
    label = "CHF + H <=> CF + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.6e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + H <=> CF + H2""",
)

entry(
    index = 117,
    label = "CHF + F <=> CF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + F <=> CF + HF""",
)

entry(
    index = 118,
    label = "CF2 + H <=> CF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.98e+13,'cm^3/(mol*s)'), n=0, Ea=(4540,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2 + H <=> CF + HF""",
)

entry(
    index = 119,
    label = "CF + O2 <=> CFO + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.62e+12,'cm^3/(mol*s)'), n=0, Ea=(1690,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF + O2 <=> CFO + O""",
)

entry(
    index = 120,
    label = "CF + H2O <=> CHFO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(17000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF + H2O <=> CHFO + H""",
)

entry(
    index = 121,
    label = "CF + O <=> CO + F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8e+13,'cm^3/(mol*s)'), n=0, Ea=(1410,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF + O <=> CO + F""",
)

entry(
    index = 122,
    label = "CF + OH <=> CO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8e+13,'cm^3/(mol*s)'), n=0, Ea=(1410,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF + OH <=> CO + HF""",
)

entry(
    index = 123,
    label = "CHF + CHF <=> C2HF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.7e+13,'cm^3/(mol*s)'), n=0, Ea=(-5000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + CHF <=> C2HF + HF""",
)

entry(
    index = 124,
    label = "C2HF + O <=> CO + CHF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+13,'cm^3/(mol*s)'), n=0, Ea=(4000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2HF + O <=> CO + CHF""",
)

entry(
    index = 125,
    label = "CH2F2 + CHF <=> CHFCHF(Z) + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+13,'cm^3/(mol*s)'), n=0, Ea=(20000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F2 + CHF <=> CHFCHF(Z) + HF""",
)

entry(
    index = 126,
    label = "CHFCHF(Z) + O <=> CH2F + CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+09,'cm^3/(mol*s)'), n=1, Ea=(1590,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFCHF(Z) + O <=> CH2F + CFO""",
)

entry(
    index = 127,
    label = "CH2F + O2 <=> CHFO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.25e+11,'cm^3/(mol*s)'), n=0, Ea=(3540,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F + O2 <=> CHFO + OH""",
)

entry(
    index = 128,
    label = "CH2F + O <=> CHFO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.7e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F + O <=> CHFO + H""",
)

entry(
    index = 129,
    label = "CH2F + OH <=> CH2O + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F + OH <=> CH2O + HF""",
)

entry(
    index = 130,
    label = "CH2F + F <=> CHF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F + F <=> CHF + HF""",
)

entry(
    index = 131,
    label = "CH3-CHF2 <=> CH2CHF + HF",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([1,2,3],'atm'), arrhenius=[Arrhenius(A=(1.6e+14,'s^-1'), n=0, Ea=(63800,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.5e+14,'s^-1'), n=0, Ea=(64700,'cal/mol'), T0=(1,'K')), Arrhenius(A=(3e+14,'s^-1'), n=0, Ea=(65100,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is CH3-CHF2 <=> CH2CHF + HF""",
)

entry(
    index = 132,
    label = "CH2CHF <=> C2H2 + HF",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([1,2,3],'atm'), arrhenius=[Arrhenius(A=(7.7e+13,'s^-1'), n=0, Ea=(71300,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.9e+14,'s^-1'), n=0, Ea=(72200,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.2e+14,'s^-1'), n=0, Ea=(72700,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is CH2CHF <=> C2H2 + HF""",
)

entry(
    index = 133,
    label = "CH3 + CHF2 <=> CH3-CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.35e+08,'cm^3/(mol*s)'), n=0, Ea=(-9614,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + CHF2 <=> CH3-CHF2""",
)

entry(
    index = 134,
    label = "CH3-CHF2 + H <=> CH3-CF2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+14,'cm^3/(mol*s)'), n=0, Ea=(19100,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + H <=> CH3-CF2 + H2""",
)

entry(
    index = 135,
    label = "CH3-CHF2 + H <=> CHF2-CH2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.17e+13,'cm^3/(mol*s)'), n=0, Ea=(15200,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + H <=> CHF2-CH2 + H2""",
)

entry(
    index = 136,
    label = "CH3-CHF2 + O <=> CH3-CF2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.17e+14,'cm^3/(mol*s)'), n=0, Ea=(16100,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + O <=> CH3-CF2 + OH""",
)

entry(
    index = 137,
    label = "CH3-CHF2 + O <=> CHF2-CH2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.38e+14,'cm^3/(mol*s)'), n=0, Ea=(18600,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + O <=> CHF2-CH2 + OH""",
)

entry(
    index = 138,
    label = "CH3-CHF2 + F <=> CH3-CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.77e+14,'cm^3/(mol*s)'), n=0, Ea=(6000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + F <=> CH3-CF2 + HF""",
)

entry(
    index = 139,
    label = "CH3-CHF2 + F <=> CHF2-CH2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.59e+15,'cm^3/(mol*s)'), n=0, Ea=(9100,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + F <=> CHF2-CH2 + HF""",
)

entry(
    index = 140,
    label = "CH3-CHF2 + OH <=> CHF2-CH2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.75e+13,'cm^3/(mol*s)'), n=0, Ea=(11700,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + OH <=> CHF2-CH2 + H2O""",
)

entry(
    index = 141,
    label = "CH3-CHF2 + OH <=> CH3-CF2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.79e+12,'cm^3/(mol*s)'), n=0, Ea=(8500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF2 + OH <=> CH3-CF2 + H2O""",
)

entry(
    index = 142,
    label = "CH3-CF2 + H <=> CH2CHF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.49e+13,'cm^3/(mol*s)'), n=0, Ea=(-1900,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + H <=> CH2CHF + HF""",
)

entry(
    index = 143,
    label = "CHF2-CH2 + H <=> CH2CHF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.9e+13,'cm^3/(mol*s)'), n=0, Ea=(-2100,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + H <=> CH2CHF + HF""",
)

entry(
    index = 144,
    label = "CH3-CF2 + H <=> CH3 + CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.43e+14,'cm^3/(mol*s)'), n=0, Ea=(10200,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + H <=> CH3 + CHF2""",
)

entry(
    index = 145,
    label = "CHF2-CH2 + H <=> CH3 + CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.85e+14,'cm^3/(mol*s)'), n=0, Ea=(8100,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + H <=> CH3 + CHF2""",
)

entry(
    index = 146,
    label = "CHF2-CH2 + H <=> CH3-CF2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.73e+13,'cm^3/(mol*s)'), n=0, Ea=(15600,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + H <=> CH3-CF2 + H""",
)

entry(
    index = 147,
    label = "CH2CF2 + H <=> CHF2-CH2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2CF2 + H <=> CHF2-CH2""",
)

entry(
    index = 148,
    label = "CH2CF2 + H <=> CH3-CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2CF2 + H <=> CH3-CF2""",
)

entry(
    index = 149,
    label = "CH2CHF + H <=> CH2F-CH2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2CHF + H <=> CH2F-CH2""",
)

entry(
    index = 150,
    label = "CH2CHF + H <=> CH3-CHF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCF': 2.0, 'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2CHF + H <=> CH3-CHF""",
)

entry(
    index = 151,
    label = "CHFCF2 + H <=> CH2F-CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """The chemkin file reaction is CHFCF2 + H <=> CH2F-CF2""",
)

entry(
    index = 152,
    label = "CHFCF2 + H <=> CHF2-CHF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """The chemkin file reaction is CHFCF2 + H <=> CHF2-CHF""",
)

entry(
    index = 153,
    label = "CH2F-CF2 + O2 <=> CHFCF2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+09,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF2 + O2 <=> CHFCF2 + HO2""",
)

entry(
    index = 154,
    label = "CHF2-CHF + O2 <=> CHFCF2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+09,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CHF + O2 <=> CHFCF2 + HO2""",
)

entry(
    index = 155,
    label = "CHF2-CF2 + O2 <=> CF2CF2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+09,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CF2 + O2 <=> CF2CF2 + HO2""",
)

entry(
    index = 156,
    label = "CF3-CHF + O2 <=> CF2CF2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+09,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + O2 <=> CF2CF2 + HO2""",
)

entry(
    index = 157,
    label = "CH3-CHF + O2 <=> CH2CHF + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+10,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF + O2 <=> CH2CHF + HO2""",
)

entry(
    index = 158,
    label = "CH2F-CH2 + O2 <=> CH2CHF + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+10,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CH2 + O2 <=> CH2CHF + HO2""",
)

entry(
    index = 159,
    label = "CH3-CF2 + O2 <=> CH2CF2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+10,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + O2 <=> CH2CF2 + HO2""",
)

entry(
    index = 160,
    label = "CHF2-CH2 + O2 <=> CH2CF2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+10,'cm^3/(mol*s)'), n=0, Ea=(-7800,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + O2 <=> CH2CF2 + HO2""",
)

entry(
    index = 161,
    label = "CH3-CF2 + H <=> CH2CF2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + H <=> CH2CF2 + H2""",
)

entry(
    index = 162,
    label = "CHF2-CH2 + H <=> CH2CF2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + H <=> CH2CF2 + H2""",
)

entry(
    index = 163,
    label = "CH3-CF2 + O <=> CH2CF2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + O <=> CH2CF2 + OH""",
)

entry(
    index = 164,
    label = "CHF2-CH2 + O <=> CH2CF2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + O <=> CH2CF2 + OH""",
)

entry(
    index = 165,
    label = "CH3-CF2 + F <=> CH2CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + F <=> CH2CF2 + HF""",
)

entry(
    index = 166,
    label = "CHF2-CH2 + F <=> CH2CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + F <=> CH2CF2 + HF""",
)

entry(
    index = 167,
    label = "CH3-CF2 + O2 => CF2O + CH3 + O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1.55e+11,'cm^3/(mol*s)'), n=0, Ea=(23000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + O2 => CF2O + CH3 + O""",
)

entry(
    index = 168,
    label = "CHF2-CH2 + O2 => CH2O + CHF2 + O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1.55e+11,'cm^3/(mol*s)'), n=0, Ea=(23000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + O2 => CH2O + CHF2 + O""",
)

entry(
    index = 169,
    label = "CH3-CHF + O2 => CHFO + CH3 + O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1.55e+11,'cm^3/(mol*s)'), n=0, Ea=(23000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF + O2 => CHFO + CH3 + O""",
)

entry(
    index = 170,
    label = "CH2F-CH2 + O2 => CH2O + CH2F + O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1.55e+11,'cm^3/(mol*s)'), n=0, Ea=(23000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CH2 + O2 => CH2O + CH2F + O""",
)

entry(
    index = 171,
    label = "CF3-CHF + O2 => CHFO + CF3 + O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1.55e+11,'cm^3/(mol*s)'), n=0, Ea=(23000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + O2 => CHFO + CF3 + O""",
)

entry(
    index = 172,
    label = "CH3-CF2 + O <=> CF2O + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + O <=> CF2O + CH3""",
)

entry(
    index = 173,
    label = "CHF2-CH2 + O <=> CH2O + CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + O <=> CH2O + CHF2""",
)

entry(
    index = 174,
    label = "CH3-CF2 + OH <=> CH2CF2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.6e+13,'cm^3/(mol*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + OH <=> CH2CF2 + H2O""",
)

entry(
    index = 175,
    label = "CHF2-CH2 + OH <=> CH2CF2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.4e+13,'cm^3/(mol*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + OH <=> CH2CF2 + H2O""",
)

entry(
    index = 176,
    label = "CH3-CF2 + HO2 => CF2O + CH3 + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CF2 + HO2 => CF2O + CH3 + OH""",
)

entry(
    index = 177,
    label = "CHF2-CH2 + HO2 => CH2O + CHF2 + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CH2 + HO2 => CH2O + CHF2 + OH""",
)

entry(
    index = 178,
    label = "CH3-CHF + HO2 => CHFO + CH3 + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3-CHF + HO2 => CHFO + CH3 + OH""",
)

entry(
    index = 179,
    label = "CH2F-CH2 + HO2 => CH2O + CH2F + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CH2 + HO2 => CH2O + CH2F + OH""",
)

entry(
    index = 180,
    label = "CF3-CHF + HO2 => CHFO + CF3 + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + HO2 => CHFO + CF3 + OH""",
)

entry(
    index = 181,
    label = "CH2CF2 <=> C2HF + HF",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(5.19e+14,'s^-1'), n=0, Ea=(86400,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.48e+39,'cm^3/(mol*s)'), n=-12.85, Ea=(87150,'cal/mol'), T0=(1,'K')), alpha=0.917, T3=(1192,'K'), T1=(39,'K'), T2=(6181,'K'), efficiencies={'CC(F)F': 2.0, 'F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH2CF2 <=> C2HF + HF""",
)

entry(
    index = 182,
    label = "CH2CHF + O <=> CH2CO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.2e+13,'cm^3/(mol*s)'), n=0, Ea=(1240,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHF + O <=> CH2CO + HF""",
)

entry(
    index = 183,
    label = "CH2CHF + O <=> CH2F + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.05e+13,'cm^3/(mol*s)'), n=0, Ea=(1240,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHF + O <=> CH2F + HCO""",
)

entry(
    index = 184,
    label = "CH2CF2 + O <=> HCO + CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.3e+09,'cm^3/(mol*s)'), n=1, Ea=(1490,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CF2 + O <=> HCO + CHF2""",
)

entry(
    index = 185,
    label = "CH2CHF + F <=> CH2CF2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+10,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHF + F <=> CH2CF2 + H""",
)

entry(
    index = 186,
    label = "CH2CHF + F <=> CHFCHF(Z) + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHF + F <=> CHFCHF(Z) + H""",
)

entry(
    index = 187,
    label = "CH2CF2 + F <=> CHFCF2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CF2 + F <=> CHFCF2 + H""",
)

entry(
    index = 188,
    label = "CHFCHF(Z) + F <=> CHFCF2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFCHF(Z) + F <=> CHFCF2 + H""",
)

entry(
    index = 189,
    label = "CH2F-CF3 <=> CHFCF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'s^-1'), n=0, Ea=(62690,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 <=> CHFCF2 + HF""",
)

entry(
    index = 190,
    label = "CH2F-CF3 + H <=> CF3-CHF + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(22000,'cm^3/(mol*s)'), n=2.87, Ea=(8000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + H <=> CF3-CHF + H2""",
)

entry(
    index = 191,
    label = "CH2F-CF3 + O <=> CF3-CHF + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(140,'cm^3/(mol*s)'), n=3.45, Ea=(6500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + O <=> CF3-CHF + OH""",
)

entry(
    index = 192,
    label = "CH2F-CF3 + OH <=> CF3-CHF + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5200,'cm^3/(mol*s)'), n=2.66, Ea=(1500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + OH <=> CF3-CHF + H2O""",
)

entry(
    index = 193,
    label = "CH2F-CF3 + CFO => CF3-CHF + CHFO",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(6000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + CFO => CF3-CHF + CHFO""",
)

entry(
    index = 194,
    label = "CH2F-CF3 + F <=> CF3-CHF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.6e+13,'cm^3/(mol*s)'), n=0, Ea=(4500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + F <=> CF3-CHF + HF""",
)

entry(
    index = 195,
    label = "CH2F-CF3 + CF3 <=> CF3-CHF + CHF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+10,'cm^3/(mol*s)'), n=0, Ea=(6400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + CF3 <=> CF3-CHF + CHF3""",
)

entry(
    index = 196,
    label = "CH2F-CF3 + CH3-CF2 <=> CF3-CHF + CH3-CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(6400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + CH3-CF2 <=> CF3-CHF + CH3-CHF2""",
)

entry(
    index = 197,
    label = "CH2F-CF3 + CHF2-CH2 <=> CF3-CHF + CH3-CHF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(6400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F-CF3 + CHF2-CH2 <=> CF3-CHF + CH3-CHF2""",
)

entry(
    index = 198,
    label = "CH2F + CF3 <=> CH2F-CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+12,'cm^3/(mol*s)'), n=0, Ea=(-4217,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2F + CF3 <=> CH2F-CF3""",
)

entry(
    index = 199,
    label = "CHF2 + CF3 <=> CF2CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+16,'cm^3/(mol*s)'), n=-1.17, Ea=(4330,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2 + CF3 <=> CF2CF2 + HF""",
)

entry(
    index = 200,
    label = "CF3-CHF <=> CHFCF2 + F",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4e+13,'s^-1'), n=0, Ea=(70000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6e+19,'cm^3/(mol*s)'), n=0, Ea=(70000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCF': 2.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5}),
    shortDesc = """The chemkin file reaction is CF3-CHF <=> CHFCF2 + F""",
)

entry(
    index = 201,
    label = "CF3-CHF + H <=> CHFCF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.56e+24,'cm^3/(mol*s)'), n=-3.57, Ea=(4225,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + H <=> CHFCF2 + HF""",
)

entry(
    index = 202,
    label = "CF3-CHF + H <=> CF3 + CH2F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.28e+16,'cm^3/(mol*s)'), n=-0.74, Ea=(4750,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + H <=> CF3 + CH2F""",
)

entry(
    index = 203,
    label = "CF3-CHF + O <=> CF3 + CHFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.4e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + O <=> CF3 + CHFO""",
)

entry(
    index = 204,
    label = "CF3-CHF + F <=> CF2CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + F <=> CF2CF2 + HF""",
)

entry(
    index = 205,
    label = "CF3-CHF + HO2 <=> CH2F-CF3 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CHF + HO2 <=> CH2F-CF3 + O2""",
)

entry(
    index = 206,
    label = "CHFCF2 <=> C2F2 + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2e+14,'s^-1'), n=0, Ea=(80000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.5e+15,'cm^3/(mol*s)'), n=1, Ea=(80000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CHFCF2 <=> C2F2 + HF""",
)

entry(
    index = 207,
    label = "CHFCF2 + O <=> CHF2 + CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+09,'cm^3/(mol*s)'), n=1, Ea=(1150,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFCF2 + O <=> CHF2 + CFO""",
)

entry(
    index = 208,
    label = "CHFCF2 + O <=> CHF + CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(800000,'cm^3/(mol*s)'), n=2, Ea=(2000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFCF2 + O <=> CHF + CF2O""",
)

entry(
    index = 209,
    label = "CHFCF2 + O <=> CF2 + CHFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(800000,'cm^3/(mol*s)'), n=2, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFCF2 + O <=> CF2 + CHFO""",
)

entry(
    index = 210,
    label = "CHFCF2 + F <=> CF2CF2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.25e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHFCF2 + F <=> CF2CF2 + H""",
)

entry(
    index = 211,
    label = "CHF + CF2 <=> C2F2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.51e+19,'cm^3/(mol*s)'), n=-2.12, Ea=(2380,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF + CF2 <=> C2F2 + HF""",
)

entry(
    index = 212,
    label = "CF2CF2 <=> CF2 + CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(5.01e+14,'s^-1'), n=0, Ea=(68070,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.96e+50,'cm^3/(mol*s)'), n=-9.06, Ea=(85300,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CF2CF2 <=> CF2 + CF2""",
)

entry(
    index = 213,
    label = "CF2CF2 + H <=> CHF2-CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(8.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.37e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CF2CF2 + H <=> CHF2-CF2""",
)

entry(
    index = 214,
    label = "CF2CF2 + O <=> CF2 + CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.01e+08,'cm^3/(mol*s)'), n=1.48, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF2CF2 + O <=> CF2 + CF2O""",
)

entry(
    index = 215,
    label = "C2F2 + O <=> CFCO + F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+07,'cm^3/(mol*s)'), n=2, Ea=(1900,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2F2 + O <=> CFCO + F""",
)

entry(
    index = 216,
    label = "CFCO + H <=> CHF + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFCO + H <=> CHF + CO""",
)

entry(
    index = 217,
    label = "CFCO + O <=> CFO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFCO + O <=> CFO + CO""",
)

entry(
    index = 218,
    label = "CFCO + F <=> CF2 + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CFCO + F <=> CF2 + CO""",
)

entry(
    index = 219,
    label = "CF3 <=> CF2 + F",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+15,'s^-1'), n=0, Ea=(82370,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5e+15,'cm^3/(mol*s)'), n=0, Ea=(59660,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CF3 <=> CF2 + F""",
)

entry(
    index = 220,
    label = "CF3 + O2 <=> CF3O + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.26e+09,'cm^3/(mol*s)'), n=1.14, Ea=(21500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3 + O2 <=> CF3O + O""",
)

entry(
    index = 221,
    label = "CF3 + H <=> CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.34e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3 + H <=> CF2 + HF""",
)

entry(
    index = 222,
    label = "CF3 + O <=> CF2O + F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.54e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3 + O <=> CF2O + F""",
)

entry(
    index = 223,
    label = "CF3 + OH <=> CF2O + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3 + OH <=> CF2O + HF""",
)

entry(
    index = 224,
    label = "CF3 + HO2 <=> CHF3 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3 + HO2 <=> CHF3 + O2""",
)

entry(
    index = 225,
    label = "CF3 + HO2 <=> CF3O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3 + HO2 <=> CF3O + OH""",
)

entry(
    index = 226,
    label = "CHF3 <=> CF2 + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.25e+15,'s^-1'), n=0, Ea=(75800,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.14e+15,'cm^3/(mol*s)'), n=0, Ea=(53500,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CHF3 <=> CF2 + HF""",
)

entry(
    index = 227,
    label = "CHF3 + H <=> CF3 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3e+14,'cm^3/(mol*s)'), n=0, Ea=(17316,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF3 + H <=> CF3 + H2""",
)

entry(
    index = 228,
    label = "CHF3 + O <=> CF3 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.19e+14,'cm^3/(mol*s)'), n=0, Ea=(17146,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF3 + O <=> CF3 + OH""",
)

entry(
    index = 229,
    label = "CHF3 + OH <=> CF3 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.64e+13,'cm^3/(mol*s)'), n=0, Ea=(8640,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF3 + OH <=> CF3 + H2O""",
)

entry(
    index = 230,
    label = "CHF3 + F <=> CF3 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.17e+14,'cm^3/(mol*s)'), n=0, Ea=(6903,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF3 + F <=> CF3 + HF""",
)

entry(
    index = 231,
    label = "CF3O <=> CF2O + F",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(9.03e+26,'cm^3/(mol*s)'), n=-3.42, Ea=(21700,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """The chemkin file reaction is CF3O <=> CF2O + F""",
)

entry(
    index = 232,
    label = "CF3O + CO <=> CO2 + CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.13e+10,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3O + CO <=> CO2 + CF3""",
)

entry(
    index = 233,
    label = "CF3O + H2O => CF2O + HF + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(5.13e+07,'cm^3/(mol*s)'), n=1.4, Ea=(6220,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3O + H2O => CF2O + HF + OH""",
)

entry(
    index = 234,
    label = "CHF2-CF3 <=> CF2CF2 + HF",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(5.5e+14,'s^-1'), n=0, Ea=(85040,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.1e+14,'s^-1'), n=0, Ea=(92970,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is CHF2-CF3 <=> CF2CF2 + HF""",
)

entry(
    index = 235,
    label = "CHF2-CF3 <=> CHF2 + CF3",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(3.53e+17,'s^-1'), n=0, Ea=(97470,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.22e+18,'cm^3/(mol*s)'), n=0, Ea=(53538,'cal/mol'), T0=(1,'K')), alpha=0.04, T3=(1e-30,'K'), T1=(1e+30,'K'), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CHF2-CF3 <=> CHF2 + CF3""",
)

entry(
    index = 236,
    label = "CHF2-CF3 + H <=> CF3-CF2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+07,'cm^3/(mol*s)'), n=1.6, Ea=(10200,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CF3 + H <=> CF3-CF2 + H2""",
)

entry(
    index = 237,
    label = "CHF2-CF3 + O <=> CF3-CF2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+07,'cm^3/(mol*s)'), n=1.6, Ea=(12700,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CF3 + O <=> CF3-CF2 + OH""",
)

entry(
    index = 238,
    label = "CHF2-CF3 + OH <=> CF3-CF2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+07,'cm^3/(mol*s)'), n=1.6, Ea=(2246,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CF3 + OH <=> CF3-CF2 + H2O""",
)

entry(
    index = 239,
    label = "CHF2-CF3 + F <=> CF3-CF2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7110,'cm^3/(mol*s)'), n=2.72, Ea=(-910,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CHF2-CF3 + F <=> CF3-CF2 + HF""",
)

entry(
    index = 240,
    label = "CF3-CF2 + O2 => CF3 + CF2O + O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(23000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CF2 + O2 => CF3 + CF2O + O""",
)

entry(
    index = 241,
    label = "CF3-CF2 + O <=> CF2O + CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CF2 + O <=> CF2O + CF3""",
)

entry(
    index = 242,
    label = "CF3-CF2 + F <=> CF3 + CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.16e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CF2 + F <=> CF3 + CF3""",
)

entry(
    index = 243,
    label = "CF3-CF2 + HO2 => CF2O + CF3 + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CF3-CF2 + HO2 => CF2O + CF3 + OH""",
)

entry(
    index = 244,
    label = "CF3 + CF3 <=> CF3-CF3",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(9.69e+10,'cm^3/(mol*s)'), n=0.77, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.12e+60,'cm^6/(mol^2*s)'), n=-12.51, Ea=(5910,'cal/mol'), T0=(1,'K')), alpha=0.069, T3=(260,'K'), T1=(880,'K'), efficiencies={'C': 2.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CF3 + CF3 <=> CF3-CF3""",
)

