#!/usr/bin/env python
# encoding: utf-8

name = "XY_Addition_MultipleBond/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["X_MultipleBond_Y"], ownReverse=False)

reverse = "XY_Elimination_MultipleBond"
reversible = True

reactantNum = 2

productNum = 1

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['FORM_BOND', '*2', 1, '*4'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *3 [H,F1s,Cl1s,Br1s]  u0 {2,S}
2 *4 [F1s,Cl1s,Br1s]    u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "YY",
    group = 
"""
1 *3 [F1s,Cl1s,Br1s]    u0 {2,S}
2 *4 [F1s,Cl1s,Br1s]    u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "HY",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 [F1s,Cl1s,Br1s]    u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "HF",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 F1s                u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "HF_Ext-3COCdCddCtO2d-R",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 F1s                u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
5    R!H                ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,[D,T]} {6,[S,D,T,B,Q]}
5    R!H ux {3,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,[D,T]} {6,[S,D,T,B,Q]}
5    R!H ux {3,[S,D,T,B,Q]}
6    F   ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,D} {5,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,D} {6,S} {7,S}
5    R!H ux {3,[S,D,T,B,Q]}
6    F   u0 {4,S}
7    F   u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F_Ext-4COCdCddCtO2d-R_Ext-3COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 r0 {2,S}
2 *4 F1s u0 r0 {1,S}
3 *1 Cd  u0 r0 {4,D} {5,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
4 *2 Cd  u0 r0 {3,D} {6,S} {7,S}
5    R!H ux {3,[S,D,T,B,Q]}
6    F   u0 r0 {4,S}
7    F   u0 r0 {4,S}
8    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F_Ext-3COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]} {5,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,[D,T]} {6,[S,D,T,B,Q]}
5    R!H ux {3,[S,D,T,B,Q]}
6    F   ux {4,[S,D,T,B,Q]}
7    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,[D,T]} {6,[S,D,T,B,Q]}
5    R!H ux {3,[S,D,T,B,Q]}
6    Br  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F_5R!H->C",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]} {5,S}
4 *2 Cd  u0 {3,[D,T]} {6,[S,D,T,B,Q]}
5    C   u0 r0 {3,S}
6    Br  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F_N-5R!H->C",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,D} {5,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,D} {6,S}
5    F   ux {3,[S,D,T,B,Q]}
6    Br  u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F_N-5R!H->C_Ext-3COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 r0 {2,S}
2 *4 F1s u0 r0 {1,S}
3 *1 Cd  u0 r0 {4,D} {5,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *2 Cd  u0 r0 {3,D} {6,S}
5    F   ux {3,[S,D,T,B,Q]}
6    Br  u0 r0 {4,S}
7    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "HF_Ext-3COCdCddCtO2d-R_3COCdCddCtO2d->Cd",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,D} {5,[S,D,T,B,Q]}
4 *2 Cd  u0 {3,D}
5    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "HF_Ext-3COCdCddCtO2d-R_3COCdCddCtO2d->Cd_Ext-3Cd-R",
    group = 
"""
1 *3 H   u0 r0 {2,S}
2 *4 F1s u0 r0 {1,S}
3 *1 Cd  u0 r0 {4,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4 *2 Cd  u0 r0 {3,D}
5    R!H ux {3,[S,D,T,B,Q]}
6    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "HF_Ext-3COCdCddCtO2d-R_N-3COCdCddCtO2d->Cd",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 F1s                u0 {1,S}
3 *1 Ct                 u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
5    R!H                ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "HF_3COCdCddCtO2d->Ct",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 F1s                u0 {1,S}
3 *1 Ct                 u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "HF_N-3COCdCddCtO2d->Ct",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 F1s                u0 {1,S}
3 *1 [Cd,O2d]           u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]}
4 *2 Cd  u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]}
4 *2 Cd  u0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R_5R!H->F",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]}
4 *2 Cd  u0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    F   ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R_5R!H->F_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 Cd  u0 {4,[D,T]}
4 *2 Cd  u0 {3,[D,T]} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    F   ux {4,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R_N-5R!H->F",
    group = 
"""
1 *3 H                      u0 r0 {2,S}
2 *4 F1s                    u0 r0 {1,S}
3 *1 Cd                     u0 r0 {4,D}
4 *2 Cd                     u0 r0 {3,D} {5,S}
5    [O,C,Si,S,N,P,I,Br,Cl] u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "HF_N-3COCdCddCtO2d->Ct_N-3CdO2d->Cd",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 F1s                u0 {1,S}
3 *1 O2d                u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "HF_N-3COCdCddCtO2d->Ct_N-3CdO2d->Cd_4COCdCddCtO2d->Cdd",
    group = 
"""
1 *3 H   u0 {2,S}
2 *4 F1s u0 {1,S}
3 *1 O2d u0 {4,[D,T]}
4 *2 Cdd u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "HF_N-3COCdCddCtO2d->Ct_N-3CdO2d->Cd_N-4COCdCddCtO2d->Cdd",
    group = 
"""
1 *3 H       u0 {2,S}
2 *4 F1s     u0 {1,S}
3 *1 O2d     u0 {4,[D,T]}
4 *2 [Cd,CO] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "HCl",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 Cl1s               u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "HCl_3COCdCddCtO2d->Cd",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]}
4 *2 Cd   u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,[D,T]}
5    R!H  ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,[D,T]}
5    Cl   ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-3Cd-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,D}
5    Cl   ux {3,[S,D,T,B,Q]}
6    Cl   ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-3Cd-R_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,D} {7,[S,D,T,B,Q]}
5    Cl   ux {3,[S,D,T,B,Q]}
6    Cl   ux {3,[S,D,T,B,Q]}
7    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-3Cd-R_Ext-4COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,D} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
5    Cl   ux {3,[S,D,T,B,Q]}
6    Cl   ux {3,[S,D,T,B,Q]}
7    R!H  ux {4,[S,D,T,B,Q]}
8    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,[D,T]} {6,[S,D,T,B,Q]}
5    Cl   ux {3,[S,D,T,B,Q]}
6    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_N-5R!H->Cl",
    group = 
"""
1 *3 H                     u0 r0 {2,S}
2 *4 Cl1s                  u0 r0 {1,S}
3 *1 Cd                    u0 r0 {4,[D,T]} {5,S}
4 *2 Cd                    u0 r0 {3,[D,T]}
5    [O,C,Si,S,N,P,F,I,Br] u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]}
4 *2 Cd   u0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 r0 {2,S}
2 *4 Cl1s u0 r0 {1,S}
3 *1 Cd   u0 r0 {4,D}
4 *2 Cd   u0 r0 {3,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    R!H  ux {4,[S,D,T,B,Q]}
6    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_5R!H->C",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]}
4 *2 Cd   u0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    C    ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_N-5R!H->C",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]}
4 *2 Cd   u0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    Cl   ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "HCl_N-3COCdCddCtO2d->Cd",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 Cl1s               u0 {1,S}
3 *1 [Ct,Cdd,CO,O2d]    u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "HCl_N-3COCdCddCtO2d->Cd_Ext-3COCddCtO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Cl1s u0 {1,S}
3 *1 Ct   u0 {4,T} {5,S}
4 *2 Ct   u0 {3,T}
5    Cl   u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "HCl_N-3COCdCddCtO2d->Cd_Ext-3COCddCtO2d-R_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 r0 {2,S}
2 *4 Cl1s u0 r0 {1,S}
3 *1 Ct   u0 r0 {4,T} {5,S}
4 *2 Ct   u0 r0 {3,T} {6,[S,D,T,B,Q]}
5    Cl   u0 r0 {3,S}
6    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "HCl_N-3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 Cl1s               u0 {1,S}
3 *1 [Ct,Cdd,CO,O2d]    u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    R!H                u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "HCl_N-3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_3COCddCtO2d->Ct",
    group = 
"""
1 *3 H                  u0 r0 {2,S}
2 *4 Cl1s               u0 r0 {1,S}
3 *1 Ct                 u0 r0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 r0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    R!H                u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "HCl_N-3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_N-3COCddCtO2d->Ct",
    group = 
"""
1 *3 H                  u0 r0 {2,S}
2 *4 Cl1s               u0 r0 {1,S}
3 *1 O2d                u0 r0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 r0 {3,[D,T]} {5,[S,D,T,B,Q]}
5    R!H                u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "HBr",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 Br1s               u0 {1,S}
3 *1 [Cd,Cdd,Ct,CO,O2d] u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "HBr_3COCdCddCtO2d->Ct",
    group = 
"""
1 *3 H                  u0 r0 {2,S}
2 *4 Br1s               u0 r0 {1,S}
3 *1 Ct                 u0 r0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 r0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "HBr_N-3COCdCddCtO2d->Ct",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 Br1s               u0 {1,S}
3 *1 [Cd,Cdd,CO,O2d]    u0 {4,[D,T]}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,[D,T]}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Br1s u0 {1,S}
3 *1 Cd   u0 {4,[D,T]} {5,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,[D,T]}
5    R!H  ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_5R!H->C",
    group = 
"""
1 *3 H    u0 r0 {2,S}
2 *4 Br1s u0 r0 {1,S}
3 *1 Cd   u0 r0 {4,[D,T]} {5,S}
4 *2 Cd   u0 r0 {3,[D,T]}
5    C    u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_N-5R!H->C",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Br1s u0 {1,S}
3 *1 Cd   u0 {4,D} {5,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,D}
5    F    ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_N-5R!H->C_Ext-3COCdCddO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Br1s u0 {1,S}
3 *1 Cd   u0 {4,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,D}
5    F    ux {3,[S,D,T,B,Q]}
6    F    ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_N-5R!H->C_Ext-3COCdCddO2d-R_Ext-4COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H    u0 {2,S}
2 *4 Br1s u0 {1,S}
3 *1 Cd   u0 {4,D} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4 *2 Cd   u0 {3,D} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
5    F    ux {3,[S,D,T,B,Q]}
6    F    ux {3,[S,D,T,B,Q]}
7    R!H  ux {4,[S,D,T,B,Q]}
8    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-4COCdCddCtO2d-R",
    group = 
"""
1 *3 H                  u0 {2,S}
2 *4 Br1s               u0 {1,S}
3 *1 [Cd,Cdd,CO,O2d]    u0 {4,D}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 {3,D} {5,[S,D,T,B,Q]}
5    R!H                u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-4COCdCddCtO2d-R_3COCdCddO2d->Cd",
    group = 
"""
1 *3 H                  u0 r0 {2,S}
2 *4 Br1s               u0 r0 {1,S}
3 *1 Cd                 u0 r0 {4,D}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 r0 {3,D} {5,[S,D,T,B,Q]}
5    R!H                u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "HBr_N-3COCdCddCtO2d->Ct_Ext-4COCdCddCtO2d-R_N-3COCdCddO2d->Cd",
    group = 
"""
1 *3 H                  u0 r0 {2,S}
2 *4 Br1s               u0 r0 {1,S}
3 *1 O2d                u0 r0 {4,D}
4 *2 [Cd,Cdd,Ct,CO,O2d] u0 r0 {3,D} {5,[S,D,T,B,Q]}
5    R!H                u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: YY
    L2: HY
        L3: HF
            L4: HF_Ext-3COCdCddCtO2d-R
                L5: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R
                    L6: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F
                        L7: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F_Ext-4COCdCddCtO2d-R
                            L8: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F_Ext-4COCdCddCtO2d-R_Ext-3COCdCddCtO2d-R
                        L7: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_6R!H->F_Ext-3COCdCddCtO2d-R
                    L6: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F
                        L7: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F_5R!H->C
                        L7: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F_N-5R!H->C
                            L8: HF_Ext-3COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R_N-6R!H->F_N-5R!H->C_Ext-3COCdCddCtO2d-R
                L5: HF_Ext-3COCdCddCtO2d-R_3COCdCddCtO2d->Cd
                    L6: HF_Ext-3COCdCddCtO2d-R_3COCdCddCtO2d->Cd_Ext-3Cd-R
                L5: HF_Ext-3COCdCddCtO2d-R_N-3COCdCddCtO2d->Cd
            L4: HF_3COCdCddCtO2d->Ct
            L4: HF_N-3COCdCddCtO2d->Ct
                L5: HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd
                    L6: HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R
                        L7: HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R_5R!H->F
                            L8: HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R_5R!H->F_Ext-4COCdCddCtO2d-R
                        L7: HF_N-3COCdCddCtO2d->Ct_3CdO2d->Cd_Ext-4COCdCddCtO2d-R_N-5R!H->F
                L5: HF_N-3COCdCddCtO2d->Ct_N-3CdO2d->Cd
                    L6: HF_N-3COCdCddCtO2d->Ct_N-3CdO2d->Cd_4COCdCddCtO2d->Cdd
                    L6: HF_N-3COCdCddCtO2d->Ct_N-3CdO2d->Cd_N-4COCdCddCtO2d->Cdd
        L3: HCl
            L4: HCl_3COCdCddCtO2d->Cd
                L5: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R
                    L6: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl
                        L7: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-3Cd-R
                            L8: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-3Cd-R_Ext-4COCdCddCtO2d-R
                                L9: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-3Cd-R_Ext-4COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R
                        L7: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_5R!H->Cl_Ext-4COCdCddCtO2d-R
                    L6: HCl_3COCdCddCtO2d->Cd_Ext-3Cd-R_N-5R!H->Cl
                L5: HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R
                    L6: HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R
                    L6: HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_5R!H->C
                    L6: HCl_3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_N-5R!H->C
            L4: HCl_N-3COCdCddCtO2d->Cd
                L5: HCl_N-3COCdCddCtO2d->Cd_Ext-3COCddCtO2d-R
                    L6: HCl_N-3COCdCddCtO2d->Cd_Ext-3COCddCtO2d-R_Ext-4COCdCddCtO2d-R
                L5: HCl_N-3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R
                    L6: HCl_N-3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_3COCddCtO2d->Ct
                    L6: HCl_N-3COCdCddCtO2d->Cd_Ext-4COCdCddCtO2d-R_N-3COCddCtO2d->Ct
        L3: HBr
            L4: HBr_3COCdCddCtO2d->Ct
            L4: HBr_N-3COCdCddCtO2d->Ct
                L5: HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R
                    L6: HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_5R!H->C
                    L6: HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_N-5R!H->C
                        L7: HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_N-5R!H->C_Ext-3COCdCddO2d-R
                            L8: HBr_N-3COCdCddCtO2d->Ct_Ext-3COCdCddO2d-R_N-5R!H->C_Ext-3COCdCddO2d-R_Ext-4COCdCddCtO2d-R_Ext-4COCdCddCtO2d-R
                L5: HBr_N-3COCdCddCtO2d->Ct_Ext-4COCdCddCtO2d-R
                    L6: HBr_N-3COCdCddCtO2d->Ct_Ext-4COCdCddCtO2d-R_3COCdCddO2d->Cd
                    L6: HBr_N-3COCdCddCtO2d->Ct_Ext-4COCdCddCtO2d-R_N-3COCdCddO2d->Cd
"""
)

