#!/usr/bin/env python
# encoding: utf-8

name = "halogens pdep reaction library"
shortDesc = "pressure dependent reactions involving one or more halogen atoms (F,Cl,Br)"
longDesc = """
Sources:

CH3Cl
Pelucchi M, Cavallotti C, Frassoldati A, Ranzi E, Glarborg P, Faravelli T.
Theoretical and kinetic modeling study of chloromethane (CH3Cl) pyrolysis and oxidation. 
Int J Chem Kinet. 2021;53:403-418
https://doi.org/10.1002/kin.21452

2-BTP
Burgess, D. R., Babushok, V. I., Linteris, G. T., & Manion, J. A. (2015). 
A Chemical Kinetic Mechanism for 2-Bromo-3,3,3-trifluoropropene (2-BTP) Flame Inhibition. 
International Journal of Chemical Kinetics, 47(9), 533?563. https://doi.org/10.1002/kin.20923
Obtained from https://onlinelibrary.wiley.com/doi/full/10.1002/kin.20923

NIST HFC mech
Valeri I. Babushok, Michael J. Hegetschweiler, Gregory T. Linteris, Donald R. Burgess, Jr., Jeffrey A. Manion, Robert R. Burrell, Michael J. Hegetschweiler
Obtained via email from Gregory T. Linteris (NIST) at the 11th U. S. National Combustion Meeting
Model for C1-C2 Hydrofluorocarbon (HFC) combustion of refrigerants

HFO-1234yf
Craig D. Needham, Phillip R. Westmoreland,
Combustion and flammability chemistry for the refrigerant HFO-1234yf (2,3,3,3-tetrafluroropropene),Combustion and Flame, Volume 184, 2017, Pages 176-185,
ISSN 0010-2180,https://doi.org/10.1016/j.combustflame.2017.06.004.

CF2BrCl
Olivier Mathieu, Charles Keesee, Claire Gregoire, and Eric L. Petersen
Experimental and Chemical Kinetics Study of the Effects of Halon 1211 (CF2BrCl) on the Laminar Flame Speed and Ignition of Light Hydrocarbons
The Journal of Physical Chemistry A 2015 119 (28), 7611-7626
DOI: 10.1021/acs.jpca.5b00959
"""
autoGenerated=False
entry(
    index = 0,
    label = "H + F <=> HF",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.7e+21,'cm^6/(mol^2*s)'), n=-2, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 1,
    label = "CH3F <=> CH2(S) + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+14,'s^-1'), n=0, Ea=(85000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.5e+16,'cm^3/(mol*s)'), n=0, Ea=(67499,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 2,
    label = "CHF + HF <=> CH2F2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3.04e+26,'cm^6/(mol^2*s)'), n=-3.26, Ea=(4060,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 3,
    label = "CHF3 <=> CF2 + HF",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(2.0484e+32,'cm^3/(mol*s)'), n=-4, Ea=(69050,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 4,
    label = "CF4 <=> CF3 + F",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(6.31e+16,'s^-1'), n=0, Ea=(128940,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(9e+34,'cm^3/(mol*s)'), n=-4.64, Ea=(122400,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 5,
    label = "CF3 <=> CF2 + F",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+15,'s^-1'), n=0, Ea=(82370,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5e+15,'cm^3/(mol*s)'), n=0, Ea=(59660,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 6,
    label = "CH2F + O2 <=> CHFO + OH",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.33e+10,'cm^3/(mol*s)'), n=0.9, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.1e+25,'cm^6/(mol^2*s)'), n=-3, Ea=(0,'cal/mol'), T0=(1,'K')), alpha=0.6, T3=(1000,'K'), T1=(70,'K'), T2=(1700,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 7,
    label = "CF3O <=> CF2O + F",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(9.03e+26,'cm^3/(mol*s)'), n=-3.42, Ea=(21700,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 8,
    label = "CF2 <=> CF + F",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(5.3e+14,'s^-1'), n=0, Ea=(118300,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.29e+15,'cm^3/(mol*s)'), n=0, Ea=(95470,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 9,
    label = "CHFO <=> CO + HF",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(2.48e+25,'cm^3/(mol*s)'), n=-3, Ea=(43000,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 10,
    label = "CO + F <=> CFO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3.09e+19,'cm^6/(mol^2*s)'), n=-1.4, Ea=(-487,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 18.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 11,
    label = "CH3-CH2F <=> C2H4 + HF",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.83e+13,'s^-1'), n=0, Ea=(59900,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(8.7e+68,'cm^3/(mol*s)'), n=-14.94, Ea=(75710,'cal/mol'), T0=(1,'K')), alpha=0.652, T3=(10,'K'), T1=(1496,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 12,
    label = "CF3 + CF3 <=> CF3-CF3",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(9.69e+10,'cm^3/(mol*s)'), n=0.77, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.12e+60,'cm^6/(mol^2*s)'), n=-12.51, Ea=(5910,'cal/mol'), T0=(1,'K')), alpha=0.069, T3=(260,'K'), T1=(880,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 13,
    label = "CF3-CHF <=> CHFCF2 + F",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(6.3e+14,'s^-1'), n=0, Ea=(62000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5.51e+19,'cm^3/(mol*s)'), n=0, Ea=(62000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 14,
    label = "CH2CHF <=> C2H2 + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(6.03e+14,'s^-1'), n=0, Ea=(73505,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.49e+16,'cm^3/(mol*s)'), n=0, Ea=(70800,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 15,
    label = "CH2CF2 <=> C2HF + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2.5e+14,'s^-1'), n=0, Ea=(86000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(9e+15,'cm^3/(mol*s)'), n=1, Ea=(86000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 16,
    label = "CHFCHF[Z] <=> C2HF + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2.5e+14,'s^-1'), n=0, Ea=(78000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(9e+15,'cm^3/(mol*s)'), n=1, Ea=(78000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 17,
    label = "CHFCF2 <=> C2F2 + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2.5e+14,'s^-1'), n=0, Ea=(100000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(9e+15,'cm^3/(mol*s)'), n=1, Ea=(100000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 18,
    label = "CF2CF2 <=> CF2 + CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(5.01e+14,'s^-1'), n=0, Ea=(68070,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.96e+50,'cm^3/(mol*s)'), n=-9.06, Ea=(85300,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 19,
    label = "CH2CHF + H <=> CH2F-CH2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 20,
    label = "CH2CHF + H <=> CH3-CHF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 21,
    label = "CH2CF2 + H <=> CHF2-CH2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 22,
    label = "CH2CF2 + H <=> CH3-CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 23,
    label = "CHFCHF[Z] + H <=> CH2F-CHF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(8.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.37e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 24,
    label = "CHFCF2 + H <=> CHF2-CHF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 25,
    label = "CHFCF2 + H <=> CH2F-CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.2e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.19e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 26,
    label = "CF2CF2 + H <=> CHF2-CF2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(8.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(990,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.37e+27,'cm^6/(mol^2*s)'), n=-2.8, Ea=(-54,'cal/mol'), T0=(1,'K')), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 27,
    label = "C2HF + H <=> CH2CF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2.8e+12,'cm^3/(mol*s)'), n=0, Ea=(2410,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.33e+27,'cm^6/(mol^2*s)'), n=-3.5, Ea=(2410,'cal/mol'), T0=(1,'K')), efficiencies={'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 5.0, 'O=C(F)F': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 28,
    label = "C2HF + H <=> CHFCH[Z]",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.4e+12,'cm^3/(mol*s)'), n=0, Ea=(2410,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.7e+26,'cm^6/(mol^2*s)'), n=-3.5, Ea=(2410,'cal/mol'), T0=(1,'K')), efficiencies={'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 5.0, 'O=C(F)F': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 29,
    label = "C2F2 + H <=> CHFCF[Z]",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2.8e+12,'cm^3/(mol*s)'), n=0, Ea=(2410,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.33e+27,'cm^6/(mol^2*s)'), n=-3.5, Ea=(2410,'cal/mol'), T0=(1,'K')), efficiencies={'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 5.0, 'O=C(F)F': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 30,
    label = "C2HF + F <=> CF2CH",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(8.4e+12,'cm^3/(mol*s)'), n=0, Ea=(2410,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(4e+27,'cm^6/(mol^2*s)'), n=-3.5, Ea=(2410,'cal/mol'), T0=(1,'K')), efficiencies={'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 5.0, 'O=C(F)F': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 31,
    label = "C2HF + F <=> CHFCF[Z]",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(8.4e+12,'cm^3/(mol*s)'), n=0, Ea=(2410,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(4e+27,'cm^6/(mol^2*s)'), n=-3.5, Ea=(2410,'cal/mol'), T0=(1,'K')), efficiencies={'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 5.0, 'O=C(F)F': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 32,
    label = "CF3CO <=> CF3 + CO",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.65e+14,'s^-1'), n=0, Ea=(12000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.05e+16,'cm^3/(mol*s)'), n=0, Ea=(9200,'cal/mol'), T0=(1,'K')), alpha=1, T3=(100,'K'), T1=(520,'K'), efficiencies={}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 33,
    label = "CF3CHO <=> CF2CO + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(30000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(8.75e+17,'cm^3/(mol*s)'), n=0, Ea=(30000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 34,
    label = "CF3CHO <=> CF3 + HCO",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4e+16,'s^-1'), n=0, Ea=(80000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.5e+21,'cm^3/(mol*s)'), n=0, Ea=(80000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 35,
    label = "CF3COF <=> CF3 + CFO",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.3e+16,'s^-1'), n=0, Ea=(90000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.76e+21,'cm^3/(mol*s)'), n=0, Ea=(90000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CF': 6.0, 'F': 2.0, 'FC(F)(F)F': 6.0, 'FC(F)F': 6.0, 'FCF': 6.0, 'O': 9.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 36,
    label = "F + F <=> F2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1e+14,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 37,
    label = "CH2CFO <=> CH2F + CO",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2e+13,'s^-1'), n=0, Ea=(30000,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2e+16,'cm^3/(mol*s)'), n=0, Ea=(30000,'cal/mol'), T0=(1,'K')), alpha=1, T3=(100,'K'), T1=(520,'K'), efficiencies={}),
    shortDesc = """From NIST HFC mech""",
)

entry(
    index = 38,
    label = "CH3-CHF2 <=> CH2CHF + HF",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([1,2,3],'atm'), arrhenius=[Arrhenius(A=(1.6e+14,'s^-1'), n=0, Ea=(63800,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.5e+14,'s^-1'), n=0, Ea=(64700,'cal/mol'), T0=(1,'K')), Arrhenius(A=(3e+14,'s^-1'), n=0, Ea=(65100,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """From CH2F2 Kinetics Library""",
)

entry(
    index = 39,
    label = "CHF2-CF3 <=> CHF2 + CF3",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(3.53e+17,'s^-1'), n=0, Ea=(97470,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.22e+18,'cm^3/(mol*s)'), n=0, Ea=(53538,'cal/mol'), T0=(1,'K')), alpha=0.04, T3=(1e-30,'K'), T1=(1e+30,'K'), efficiencies={'C': 2.0, 'CC(F)F': 2.0, 'F': 2.0, 'FC(F)F': 2.0, 'FCC(F)(F)F': 2.0, 'FCF': 2.0, 'O': 6.0, 'O=C(F)F': 5.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CH2F2 Kinetics Library""",
)

entry(
    index = 40,
    label = "CH2CF + CF3 <=> CH2CFCF3",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(6.812e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.526e+18,'cm^6/(mol^2*s)'), n=-14.527, Ea=(9004,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From HFO-1234yf mech""",
)

entry(
    index = 41,
    label = "CH2CFCF3 <=> CF3CCH + HF",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.568e+10,'s^-1'), n=1.209, Ea=(79606,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(9.663e+47,'cm^3/(mol*s)'), n=-15.43, Ea=(88107,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From HFO-1234yf mech""",
)

entry(
    index = 42,
    label = "E-CHCFCF3 + O <=> CHOCFCF3",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(2.581e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.775e+31,'cm^6/(mol^2*s)'), n=-17.096, Ea=(9613,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From HFO-1234yf mech""",
)

entry(
    index = 44,
    label = "CH3CFCF3 + O <=> CH3COFCF3",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.704e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.389e+39,'cm^6/(mol^2*s)'), n=-19.805, Ea=(12618,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From HFO-1234yf mech""",
)

entry(
    index = 45,
    label = "CF3CFCO + H <=> CHOCFCF3",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(8.359e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.595e+15,'cm^6/(mol^2*s)'), n=-13.955, Ea=(4591,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From HFO-1234yf mech""",
)

entry(
    index = 46,
    label = "BR + BR <=> BR2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.92e+14,'cm^6/(mol^2*s)'), n=0, Ea=(-1700,'cal/mol'), T0=(1,'K')), efficiencies={'BrBr': 14.0, 'C': 1.5, 'FC(F)(F)Br': 3.0, 'O': 5.4, 'O=C=O': 2.3, '[C-]#[O+]': 1.15, '[O][O]': 1.15}),
    shortDesc = """From 2-BTP mech""",
)

entry(
    index = 47,
    label = "H + BR <=> HBR",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(4.78e+21,'cm^6/(mol^2*s)'), n=-1.963, Ea=(510.5,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From 2-BTP mech""",
)

entry(
    index = 48,
    label = "BROH <=> OH + BR",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+15,'s^-1'), n=0, Ea=(48733,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.3e+22,'cm^3/(mol*s)'), n=-1.52, Ea=(51140,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From 2-BTP mech""",
)

entry(
    index = 49,
    label = "BR + O <=> BRO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3e+13,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From 2-BTP mech""",
)

entry(
    index = 50,
    label = "C2H3BR <=> C2H2 + HBR",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(8.2e+18,'cm^3/(mol*s)'), n=0, Ea=(59750,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From 2-BTP mech""",
)

entry(
    index = 51,
    label = "CF2BR + BR <=> CF2BR2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(6e+14,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
    longDesc = """Horwitz et al. J Chem Phys 74 1981 5008""",
)

entry(
    index = 52,
    label = "CL + CL <=> CL2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(2e+14,'cm^6/(mol^2*s)'), n=0, Ea=(-1790,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
    longDesc = """Allendorf 2001""",
)

entry(
    index = 53,
    label = "H + CF2CL <=> CHF2CL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(5.01e+13,'cm^6/(mol^2*s)'), n=0, Ea=(3990,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 54,
    label = "H + CL <=> HCL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(5.3e+21,'cm^6/(mol^2*s)'), n=-2, Ea=(-2000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 55,
    label = "COCL2 <=> CCLO + CL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.2e+16,'cm^3/(mol*s)'), n=0, Ea=(75500,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 56,
    label = "CH3CHCL <=> C2H3CL + H",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.94e+09,'s^-1'), n=1.22, Ea=(38800,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.58e+40,'cm^3/(mol*s)'), n=-6.82, Ea=(43700,'cal/mol'), T0=(1,'K')), alpha=0.6702, T3=(1222,'K'), T1=(299,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 57,
    label = "CH2CLCHCL <=> CHCLCHCL + H",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.94e+09,'s^-1'), n=1.22, Ea=(38800,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.58e+40,'cm^3/(mol*s)'), n=-6.82, Ea=(43700,'cal/mol'), T0=(1,'K')), alpha=0.6702, T3=(1222,'K'), T1=(299,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 58,
    label = "CH3CCL2 <=> CH2CCL2 + H",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.94e+09,'s^-1'), n=1.22, Ea=(38800,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.58e+40,'cm^3/(mol*s)'), n=-6.82, Ea=(43700,'cal/mol'), T0=(1,'K')), alpha=0.6702, T3=(1222,'K'), T1=(299,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 59,
    label = "C2CL3 <=> C2CL2 + CL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(8e+14,'cm^3/(mol*s)'), n=0, Ea=(28000,'cal/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'CCl': 3.0, 'ClC(Cl)(Cl)Cl': 3.0, 'ClC(Cl)Cl': 3.0, 'ClCCl': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 60,
    label = "CF3CL <=> CF3 + CL",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(7.24e+19,'s^-1'), n=-1.1, Ea=(92090,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(7.81e+24,'cm^3/(mol*s)'), n=-10.83, Ea=(101000,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 61,
    label = "CF2CL2 <=> CL + CF2CL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(8.07e+16,'cm^3/(mol*s)'), n=0, Ea=(63000,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 62,
    label = "CL + CF2 <=> CF2CL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3.6e+17,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 63,
    label = "F + CCL2 <=> CFCL2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.5e+17,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 64,
    label = "FCL <=> F + CL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3e+14,'cm^3/(mol*s)'), n=0, Ea=(57500,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 65,
    label = "CFO + CL <=> CFCLO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1e+16,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 66,
    label = "CCLO + F <=> CFCLO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1e+16,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 67,
    label = "BR + CF2 <=> CF2BR",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3.6e+17,'cm^6/(mol^2*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CF2BrCl Kinetics Library""",
)

entry(
    index = 68,
    label = "OH + CL <=> HOCL",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.2e+19,'cm^6/(mol^2*s)'), n=-1.43, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CH3Cl Kinetics Library""",
)

entry(
    index = 69,
    label = "O2 + CL <=> CLOO",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6e+28,'cm^6/(mol^2*s)'), n=-5.34, Ea=(1341,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CH3Cl Kinetics Library""",
)

entry(
    index = 70,
    label = "CO + CL <=> CCLO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.2e+24,'cm^6/(mol^2*s)'), n=-3.8, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CH3Cl Kinetics Library""",
)

entry(
    index = 71,
    label = "CH3CL <=> CH3 + CL",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([0.1,1,2,5,10,20,50],'atm'), arrhenius=[Arrhenius(A=(1.218e+44,'s^-1'), n=-9.175, Ea=(94303.5,'cal/mol'), T0=(1,'K')), Arrhenius(A=(3.283e+44,'s^-1'), n=-9.011, Ea=(95477.7,'cal/mol'), T0=(1,'K')), Arrhenius(A=(2.534e+44,'s^-1'), n=-8.887, Ea=(95909.6,'cal/mol'), T0=(1,'K')), Arrhenius(A=(4.219e+44,'s^-1'), n=-8.837, Ea=(96706.9,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.018e+44,'s^-1'), n=-8.58, Ea=(96837,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.327e+43,'s^-1'), n=-8.246, Ea=(96882.5,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.272e+42,'s^-1'), n=-7.857, Ea=(97025.6,'cal/mol'), T0=(1,'K'))]),
    shortDesc = """From CH3Cl Kinetics Library""",
)

entry(
    index = 72,
    label = "CH2CL2 <=> CH2CL + CL",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.3e+16,'s^-1'), n=0, Ea=(77500,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(4e+15,'cm^3/(mol*s)'), n=0, Ea=(56400,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CH3Cl Kinetics Library""",
)

entry(
    index = 73,
    label = "C2H3CL <=> C2H2 + HCL",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1e+14,'s^-1'), n=0, Ea=(69400,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5.3e+16,'cm^3/(mol*s)'), n=0, Ea=(48700,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CH3Cl Kinetics Library""",
)

entry(
    index = 74,
    label = "C2H2 + CL <=> CHCLCH",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(4.8e+16,'cm^3/(mol*s)'), n=-1.04, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.9e+23,'cm^6/(mol^2*s)'), n=-2.09, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={}),
    shortDesc = """From CH3Cl Kinetics Library""",
)

