#!/usr/bin/env python
# encoding: utf-8

name = "1,2_shiftC/groups"
shortDesc = ""
longDesc = """
1,2-methyl shift from a Carbon to another Carbon.
Could possibly be generalized to include  1,2-methyl shift from an Oxygen to Carbon and vice versa.
1,2-methyl shift from Sulfur to Carbon has separate family (1,2_shiftS).
"""

template(reactants=["Root"], products=["cCCJ"], ownReverse=True)

reversible = True

reverseMap = {'*1': '*1', '*2': '*3', '*3': '*2'}

reactantNum = 1
productNum = 1

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['GAIN_RADICAL', '*2', '1'],
    ['LOSE_RADICAL', '*3', '1'],
])

boundaryAtoms = ["*1", "*3"]

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *1 C u0 c0 {1,S}
3 *3 C u1 {1,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_2C-inRing",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *1 C u0 c0 r1 {1,S}
3 *3 C u1 {1,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_2C-inRing_Ext-3C-R_Ext-4R!H-R_Ext-4R!H-R_Ext-4R!H-R_Ext-4R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,S} {4,[S,D,T,B,Q]}
2 *1 C   u0 c0 r1 {1,S}
3 *3 C   u1 {1,S}
4    C   ux r1 {1,[S,D,T,B,Q]} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    R!H ux {4,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_N-2C-inRing",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S}
3 *3 C u1 {1,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-2C-inRing_Ext-2C-R",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S} {4,T}
3 *3 C u1 {1,S}
4    C u0 {2,T}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_N-2C-inRing_Ext-2C-R_Ext-3C-R_Sp-5R!H-3C",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S} {4,T}
3 *3 C u1 r1 {1,S} {5,S}
4    C u0 r0 {2,T}
5    C u0 r1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-2C-inRing_Ext-2C-R_Ext-3C-R_N-Sp-5R!H-3C",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S} {4,T}
3 *3 C u1 r1 {1,S} {5,[B,D,T,Q]}
4    C u0 r0 {2,T}
5    C u0 r1 {3,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-2C-inRing_1C-inRing",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S}
3 *3 C u1 {1,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_N-2C-inRing_1C-inRing_Ext-1C-R_Ext-4R!H-R_Ext-4R!H-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,S} {4,S}
2 *1 C   u0 c0 r0 {1,S}
3 *3 C   u1 {1,S}
4    C   u0 r1 {1,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    R!H ux {4,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-2C-inRing_1C-inRing_3C-inRing",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S}
3 *3 C u1 r1 {1,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_N-2C-inRing_1C-inRing_N-3C-inRing",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S}
3 *3 C u1 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-2C-inRing_N-1C-inRing",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S}
2 *1 C u0 c0 r0 {1,S}
3 *3 C u1 {1,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_2C-inRing
        L3: Root_2C-inRing_Ext-3C-R_Ext-4R!H-R_Ext-4R!H-R_Ext-4R!H-R_Ext-4R!H-R
    L2: Root_N-2C-inRing
        L3: Root_N-2C-inRing_Ext-2C-R
            L4: Root_N-2C-inRing_Ext-2C-R_Ext-3C-R_Sp-5R!H-3C
            L4: Root_N-2C-inRing_Ext-2C-R_Ext-3C-R_N-Sp-5R!H-3C
        L3: Root_N-2C-inRing_1C-inRing
            L4: Root_N-2C-inRing_1C-inRing_Ext-1C-R_Ext-4R!H-R_Ext-4R!H-R
            L4: Root_N-2C-inRing_1C-inRing_3C-inRing
            L4: Root_N-2C-inRing_1C-inRing_N-3C-inRing
        L3: Root_N-2C-inRing_N-1C-inRing
"""
)

