#!/usr/bin/env python
# encoding: utf-8

name = "alkene_chemistry"
shortDesc = "Rate constants collected from the literature for predicting OH/HO2 addition to alkenes."
longDesc = """
[1] Yang, Feiyu, et al. "Kinetics of hydrogen abstraction and addition reactions of
    3-hexene by OH radicals." *The Journal of Physical Chemistry A* 121.9 (2017):
    1877-1889.
    CCSD(T)/CBS//BHandHLYP/6-311G(d,p) 1DHR.
[2] Villano, Stephanie M., Hans-Heinrich Carstensen, and Anthony M. Dean. "Rate rules,
    branching ratios, and pressure dependence of the HO2+ olefin addition channels."
    *The Journal of Physical Chemistry A* 117.30 (2013): 6458-6473.
    Per additional site; CBS-QB3 1DHR
[3] Xiao, FengXia, et al. "Theoretical Study of Radical–Molecule Reactions with Negative
    Activation Energies in Combustion: Hydroxyl Radical Addition to Alkenes." *ACS omega*
    5.22 (2020): 12777-12788;
    CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 hindered rotor approximation
[4] Ye, Lili, Lidong Zhang, and Fei Qi. "Ab initio kinetics on low temperature oxidation
    of iso-pentane: the first oxygen addition." *Combustion and Flame* 190 (2018): 119-132.
    QCISD(T)/CBS//B3LYP/6-311++G(d,p) with 1DHR approximation
[5] Zhou, Chong-Wen, et al. "Chemical kinetics of hydrogen atom abstraction from allylic
    sites by 3O2; implications for combustion modeling and simulation." *The Journal of
    Physical Chemistry A* 121.9 (2017): 1890-1899;
    G4//M06-2X/6-311++G(d,p) with 1DHR approximation
[6] Power, Jennifer, et al. "Hierarchical Study of the Reactions of Hydrogen Atoms with
    Alkenes: A Theoretical Study of the Reactions of Hydrogen Atoms with C2–C4 Alkenes."
    *The Journal of Physical Chemistry A* (2021);
    CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p))
"""
autoGenerated=False
entry(
    index = 0,
    label = "hexene-3 + OH <=> hex-3-enyl-1 + H2O",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(83705.8,'cm^3/(mol*s)'), n=2.59, Ea=(3.27,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BHandHLYP/6-311G(d,p) from [1] by Yang et al.""",
)

entry(
    index = 1,
    label = "hexene-3 + OH <=> hex-3-enyl-3 + H2O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1445.28,'cm^3/(mol*s)'), n=3.14, Ea=(3.36,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BHandHLYP/6-311G(d,p) from [1] by Yang et al.""",
)

# entry(
#     index = 2,
#     label = "hexene-3 + OH <=> hex-3-enyl-2 + H2O",
#     degeneracy = 4.0,
#     kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(8129.7,'cm^3/(mol*s)'), n=2.99, Ea=(2.79,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(5672.72,'cm^3/(mol*s)'), n=2.98, Ea=(2.74,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'))], Tmin=(300,'K'), Tmax=(2000,'K')),
#     shortDesc = """calculated at CCSD(T)/CBS//BHandHLYP/6-311G(d,p) from [1] by Yang et al.""",
# )

# entry(
#     index = 3,
#     label = "hexene-3 + OH <=> C6H12OH3-4J",
#     degeneracy = 2.0,
#     kinetics = PDepArrhenius(pressures=([0.001,0.01,0.1,1,10,100,1000],'atm'), arrhenius=[Arrhenius(A=(228.234,'cm^3/(mol*s)'), n=2.25, Ea=(-2.58,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(601.598,'cm^3/(mol*s)'), n=2.24, Ea=(-2.55,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(1565.72,'cm^3/(mol*s)'), n=2.24, Ea=(-2.51,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(4341.86,'cm^3/(mol*s)'), n=2.22, Ea=(-2.43,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(1391.08,'cm^3/(mol*s)'), n=2.18, Ea=(-2.27,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(54740,'cm^3/(mol*s)'), n=2.1, Ea=(-1.96,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Arrhenius(A=(128871,'cm^3/(mol*s)'), n=2.08, Ea=(-1.61,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'))], highPlimit=Arrhenius(A=(124053,'cm^3/(mol*s)'), n=2.15, Ea=(-1.4,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K')), Tmin=(300,'K'), Tmax=(2000,'K')),
#     shortDesc = """calculated at CCSD(T)/CBS//BHandHLYP/6-311G(d,p) from [1] by Yang et al.""",
# )

# entry(
#     index = 4,
#     label = "C4H8-1 + HO2 <=> nC4H8OOJ-1",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.195,'cm^3/(mol*s)'), n=3.37, Ea=(9.1,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 5,
#     label = "C3H6 + HO2 <=> C3H6OOJ-1",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.47,'cm^3/(mol*s)'), n=3.27, Ea=(9.8,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 6,
#     label = "C2H4 + HO2 <=> C2H4OO",
#     degeneracy = 2.0,
#     kinetics = Arrhenius(A=(1.002,'cm^3/(mol*s)'), n=3.27, Ea=(7.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al. A is multiplied by 2 as the reported value is per additional site.""",
# )

# entry(
#     index = 7,
#     label = "isopentene + HO2 <=> C2CCCOO",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.132,'cm^3/(mol*s)'), n=3.44, Ea=(8.6,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 8,
#     label = "C5H10-1 + HO2 <=> CCCCCOO",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.153,'cm^3/(mol*s)'), n=3.42, Ea=(9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 9,
#     label = "iC4H8 + HO2 <=> C2CCOO",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.153,'cm^3/(mol*s)'), n=3.42, Ea=(9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 10,
#     label = "iC5H10-1 + HO2 <=> iC5H11OOJ-1",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.0494,'cm^3/(mol*s)'), n=3.53, Ea=(10.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 11,
#     label = "CCCC(C)=C + HO2 <=> iC6H13OOJ-1",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.0496,'cm^3/(mol*s)'), n=3.52, Ea=(10.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 12,
#     label = "C3H6 + HO2 <=> C2COO",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.657,'cm^3/(mol*s)'), n=3.23, Ea=(5.6,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 13,
#     label = "C4H8-1 + HO2 <=> nC4H9OOJ-2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.476,'cm^3/(mol*s)'), n=3.27, Ea=(5.4,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 14,
#     label = "isopentene + HO2<=> iC5H11OOJ-3",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.289,'cm^3/(mol*s)'), n=3.33, Ea=(5.3,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 15,
#     label = "C5H10-1 + HO2 <=> nC5H11OOJ-2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.427,'cm^3/(mol*s)'), n=3.31, Ea=(5.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 16,
#     label = "C4H8-2 + HO2 <=> nC4H9OOJ-2",
#     degeneracy = 2.0,
#     kinetics = Arrhenius(A=(2.3,'cm^3/(mol*s)'), n=3.26, Ea=(7.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al. A is multiplied by 2 as the reported value is per additional site.""",
# )

# entry(
#     index = 17,
#     label = "C5H10-2 + HO2 <=> C5H11OOJ-3",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.341,'cm^3/(mol*s)'), n=3.31, Ea=(7.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 18,
#     label = "C5H10-2 + HO2 <=> nC5H11OOJ-2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.247,'cm^3/(mol*s)'), n=3.35, Ea=(6.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 19,
#     label = "iC6H12-2 + HO2 <=> iC6H13OOJ-3",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.0257,'cm^3/(mol*s)'), n=3.63, Ea=(8.2,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 20,
#     label = "iC5H10-2 + HO2 <=> iC5H11OOJ-3",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.0501,'cm^3/(mol*s)'), n=3.55, Ea=(8.7,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 21,
#     label = "CCC(C)=CC + HO2 <=> CCC(C)C(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.027,'cm^3/(mol*s)'), n=3.69, Ea=(7.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 22,
#     label = "iC4H8 + HO2 <=> CC(C)(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.794,'cm^3/(mol*s)'), n=3.2, Ea=(3.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 23,
#     label = "iC5H10-1 + HO2 <=> iC5H11OOJ-2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.146,'cm^3/(mol*s)'), n=3.4, Ea=(3.4,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 24,
#     label = "CCC(CC)=C + HO2 <=> CCC(CC)(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.0287,'cm^3/(mol*s)'), n=3.53, Ea=(2.7,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 25,
#     label = "iC5H10-2 + HO2 <=> iC5H11OOJ-2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.171,'cm^3/(mol*s)'), n=3.42, Ea=(5.2,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 26,
#     label = "CCC(C)=CC + HO2 <=> CCC(CC)(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.0546,'cm^3/(mol*s)'), n=3.63, Ea=(4.7,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 27,
#     label = "iC6H12-2 + HO2 <=> CCCC(C)(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.103,'cm^3/(mol*s)'), n=3.45, Ea=(4.6,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 28,
#     label = "CC(C)=C(C)C + HO2 <=> CC(C)C(C)(C)O[O]",
#     degeneracy = 2.0,
#     kinetics = Arrhenius(A=(0.01404,'cm^3/(mol*s)'), n=3.82, Ea=(5.7,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al. A is multiplied by 2 as the reported value is per additional site.""",
# )

# entry(
#     index = 29,
#     label = "CCC(C)=C(C)C + HO2 <=> CCC(C)C(C)(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.00223,'cm^3/(mol*s)'), n=3.95, Ea=(5.6,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

# entry(
#     index = 30,
#     label = "CCC(C)=C(C)C + HO2 <=> CC(C)C(CC)(C)O[O]",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.00893,'cm^3/(mol*s)'), n=3.76, Ea=(5.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
#     shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
# )

entry(
    index = 31,
    label = "C2H4 + HO2 <=> CJCOOH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(71.2,'cm^3/(mol*s)'), n=3.22, Ea=(11.1,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al. A is multiplied by 2 as the reported value is per additional site.""",
)

entry(
    index = 32,
    label = "C3H6 + HO2 <=> CCJCOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2560,'cm^3/(mol*s)'), n=2.62, Ea=(9.7,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 33,
    label = "C4H8-1 + HO2 <=> CCCJCOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2560,'cm^3/(mol*s)'), n=2.62, Ea=(9.7,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 34,
    label = "isopentene + HO2 <=> CC(C)[CH]COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(301,'cm^3/(mol*s)'), n=2.86, Ea=(9.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 35,
    label = "C6H12-1 + HO2 <=> CCC[CH]CCOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(442,'cm^3/(mol*s)'), n=2.88, Ea=(9.4,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 36,
    label = "iC4H8 + HO2 <=> C[C](C)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(16400,'cm^3/(mol*s)'), n=2.43, Ea=(8.3,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 37,
    label = "iC5H10-1 + HO2 <=> CC[C](C)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2990,'cm^3/(mol*s)'), n=2.55, Ea=(7.8,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 38,
    label = "CCCC(C)=C + HO2 <=> CCC[C](C)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1120,'cm^3/(mol*s)'), n=2.65, Ea=(8,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 39,
    label = "C3H6 + HO2 <=> C[C](C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(23.4,'cm^3/(mol*s)'), n=3.21, Ea=(9.1,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 40,
    label = "C4H8-1 + HO2 <=> CCC([CH2])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(20.9,'cm^3/(mol*s)'), n=3.21, Ea=(9.2,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 41,
    label = "isopentene + HO2 <=> CC(C)C([CH2])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(25.1,'cm^3/(mol*s)'), n=3.74, Ea=(8.8,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 42,
    label = "C5H10-1 + HO2 <=> CCCC([CH2])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19.5,'cm^3/(mol*s)'), n=3.22, Ea=(9.1,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 43,
    label = "C4H8-2 + HO2 <=> C[CH]C(C)OO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(774,'cm^3/(mol*s)'), n=2.89, Ea=(7.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al. A is multiplied by 2 as the reported value is per additional site.""",
)

entry(
    index = 44,
    label = "C5H10-2 + HO2 <=> C[CH]C(CC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(171,'cm^3/(mol*s)'), n=2.94, Ea=(7.4,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 45,
    label = "C5H10-2 + HO2 <=> CC[CH]C(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(49.5,'cm^3/(mol*s)'), n=3.13, Ea=(7.3,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 46,
    label = "iC6H12-2 + HO2 <=> C[C](C)C(CC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(32.7,'cm^3/(mol*s)'), n=3.16, Ea=(5.2,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 47,
    label = "iC5H10-2 + HO2 <=> C[C](C)C(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3090,'cm^3/(mol*s)'), n=2.61, Ea=(5.8,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 48,
    label = "CCC(C)=CC + HO2 <=> CC[C](C)C(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(314,'cm^3/(mol*s)'), n=2.9, Ea=(5.8,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 49,
    label = "iC4H8 + HO2 <=> CC(C)([CH2])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.19,'cm^3/(mol*s)'), n=3.28, Ea=(7.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 50,
    label = "iC5H10-1 + HO2 <=> CCC(C)([CH2])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.949,'cm^3/(mol*s)'), n=3.54, Ea=(7.3,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 51,
    label = "CCC(CC)=C + HO2 <=> CCC(CC)([CH2])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000881,'cm^3/(mol*s)'), n=4.38, Ea=(6.1,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 52,
    label = "iC5H10-2 + HO2 <=> C[CH]C(C)(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.31,'cm^3/(mol*s)'), n=3.44, Ea=(5.2,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 53,
    label = "CCC(C)=CC + HO2 <=> C[CH]C(CC)(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.107,'cm^3/(mol*s)'), n=3.81, Ea=(4.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 54,
    label = "CC(C)=C(C)C + HO2 <=> C[C](C)C(C)(C)OO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(39.2,'cm^3/(mol*s)'), n=3.18, Ea=(3,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al. A is multiplied by 2 as the reported value is per additional site.""",
)

entry(
    index = 55,
    label = "CCC(C)=C(C)C + HO2 <=> CC[C](C)C(C)(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.497,'cm^3/(mol*s)'), n=3.6, Ea=(2.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 56,
    label = "CCC(C)=C(C)C + HO2 <=> C[C](C)C(CC)(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.316,'cm^3/(mol*s)'), n=3.62, Ea=(2.5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 57,
    label = "iC6H12-2 + HO2 <=> CC[CH]C(C)(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.586,'cm^3/(mol*s)'), n=3.53, Ea=(5,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at CBS-QB3 1DHR from [2] by Villano et al.""",
)

entry(
    index = 58,
    label = "C2H4 + OH <=> [CH2]CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.84e-18,'cm^3/(molecule*s)'), n=2.03, Ea=(1.90,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) G09 Hindered rotor approximation from [3] by Xiao et al.
Cited from the Supplementary Information Table S6. A is multiplied by 2 as the reported value is per additional site.""",
)

entry(
    index = 59,
    label = "C3H6 + OH <=> [CH2]C(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.91e-19,'cm^3/(molecule*s)'), n=2.05, Ea=(-2.39,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 60,
    label = "C4H8-1 + OH <=> CCC([CH2])O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.11e-19,'cm^3/(molecule*s)'), n=2.12, Ea=(-2.43,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 61,
    label = "C5H10-1 + OH <=> CCCC([CH2])O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.61e-22,'cm^3/(molecule*s)'), n=3.03, Ea=(-2.70,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 62,
    label = "iC4H8 + OH <=> CC(C)([CH2])O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.26e-17,'cm^3/(molecule*s)'), n=2.06, Ea=(-2.50,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 63,
    label = "iC5H10-1 + OH <=> CCC(C)([CH2])O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e-19,'cm^3/(molecule*s)'), n=2.04, Ea=(-1.96,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 64,
    label = "CCCC(C)=C + OH <=> CCCC(C)([CH2])O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.17e-20,'cm^3/(molecule*s)'), n=2.06, Ea=(-2.45,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 65,
    label = "C4H8-2 + OH <=> C[CH]C(C)O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.24e-18,'cm^3/(molecule*s)'), n=1.84, Ea=(-3.19,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al.
Cited from the Supplementary Information Table S6. A is multiplied by 2 as the reported value is per additional site. Value is for trans-but-2-ene.""",
)

entry(
    index = 66,
    label = "C5H10-2 + OH <=> C[CH]C(CC)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.26e-23,'cm^3/(molecule*s)'), n=3.36, Ea=(-3.25,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 67,
    label = "C5H10-2 + OH <=> CC[CH]C(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.36e-17,'cm^3/(molecule*s)'), n=1.44, Ea=(-2.69,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 68,
    label = "iC4H8 + OH <=> C[C](C)CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.27e-20,'cm^3/(molecule*s)'), n=2.45, Ea=(-3.14,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 69,
    label = "iC5H10-1 + OH <=> CC[C](C)CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e-16,'cm^3/(molecule*s)'), n=1.28, Ea=(-2.58,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 70,
    label = "CCCC(C)=C + OH <=> CCC[C](C)CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.28e-21,'cm^3/(molecule*s)'), n=2.48, Ea=(-3.25,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 71,
    label = "C3H6 + OH <=> C[CH]CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.91e-19,'cm^3/(molecule*s)'), n=2.05, Ea=(-2.39,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 72,
    label = "C4H8-1 + OH <=> CC[CH]CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.45e-17,'cm^3/(molecule*s)'), n=1.37, Ea=(-2.03,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 73,
    label = "C5H10-1 + OH <=> CCC[CH]CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.24e-17,'cm^3/(molecule*s)'), n=1.35, Ea=(-2.07,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 74,
    label = "iC5H10-2 + OH <=> C[CH]C(C)(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.07e-17,'cm^3/(molecule*s)'), n=1.58, Ea=(-3.19,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 75,
    label = "iC6H12-2 + OH <=> CC[CH]C(C)(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.26e-20,'cm^3/(molecule*s)'), n=2.44, Ea=(-14.91,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.
The original unit is kcal/mol but Xiaorui Dong corrected it to kJ/mol.""",
)

entry(
    index = 76,
    label = "iC5H10-2 + OH <=> C[C](C)C(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.16e-21,'cm^3/(molecule*s)'), n=2.98, Ea=(-4.17,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.""",
)

entry(
    index = 77,
    label = "iC6H12-2 + OH <=> C[C](C)C(CC)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.43e-20,'cm^3/(molecule*s)'), n=2.41, Ea=(-16.23,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.
The original unit is kcal/mol but Xiaorui Dong corrected it to kJ/mol.""",
)

entry(
    index = 78,
    label = "CC=C(CC)CC + OH <=> CC[C](CC)C(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.88e-20,'cm^3/(molecule*s)'), n=2.41, Ea=(-15.52,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.
The original unit is kcal/mol but Xiaorui Dong corrected it to kJ/mol.""",
)

entry(
    index = 79,
    label = "CC(C)=C(C)C + OH <=> C[C](C)C(C)(C)O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.08e-20,'cm^3/(molecule*s)'), n=2.39, Ea=(-19.2,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.
The original unit is kcal/mol but Xiaorui Dong corrected it to kJ/mol. A is multiplied by 2 as the reported value is per additional site.""",
)

entry(
    index = 80,
    label = "CCC(C)=C(C)C + OH <=> CC[C](C)C(C)(C)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.06e-20,'cm^3/(molecule*s)'), n=2.39, Ea=(-18.27,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.
The original unit is kcal/mol but Xiaorui Dong corrected it to kJ/mol.""",
)

entry(
    index = 81,
    label = "CCC(C)=C(C)C + OH <=> C[C](C)C(C)(CC)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.29e-19,'cm^3/(molecule*s)'), n=2.39, Ea=(-18.58,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//BH&HLYP/6-311+G(d,p) with G09 Hindered rotor approximation from [3] by Xiao et al. Cited from the Supplementary Information Table S6.
The original unit is kcal/mol but Xiaorui Dong corrected it to kJ/mol.""",
)

entry(
    index = 82,
    label = "iC5H11J-1 + O2 <=> iC5H11OOJ-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.04e-14*6.022e23,'cm^3/(mol*s)'), n=0.61, Ea=(0.469,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at MRCI(7e,5o)/CBS//CASSCF(7e,5o)/cc-pVDZ from [4] by Ye et al.""",
)

entry(
    index = 83,
    label = "iC5H11OOJ-1 <=> CCC([CH2])COO",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1180,'1/s'), n=2.5, Ea=(19.073,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 84,
    label = "iC5H11OOJ-1 <=> CC[C](C)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8140,'1/s'), n=2.34, Ea=(24.345,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 85,
    label = "iC5H11OOJ-1 <=> C[CH]C(C)COO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2810,'1/s'), n=2.22, Ea=(16.431,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 86,
    label = "iC5H11OOJ-1 <=> [CH2]CC(C)COO",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(3570,'1/s'), n=2.66, Ea=(18.496,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 87,
    label = "iC5H11J-4 + O2 <=> C2CCCOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.17e-15*6.022e23,'cm^3/(mol*s)'), n=0.83, Ea=(0.279,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at MRCI(7e,5o)/CBS//CASSCF(7e,5o)/cc-pVDZ 1DHR from [4] by Ye et al.""",
)

entry(
    index = 88,
    label = "C2CCCOO <=> CC(C)[CH]COO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4790,'1/s'), n=2.6, Ea=(27.506,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 89,
    label = "C2CCCOO <=> C[C](C)CCOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(31400,'1/s'), n=2.08, Ea=(15.407,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 90,
    label = "C2CCCOO <=> [CH2]C(C)CCOO",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(573,'1/s'), n=2.47, Ea=(19.74,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 91,
    label = "iC5H11OOJ-1 <=> OH + O=CC(C)CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(213000,'1/s'), n=2.29, Ea=(36.571,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 92,
    label = "CCC([CH2])COO <=> OH + C1OCC1CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.29e+09,'1/s'), n=0.67, Ea=(18.154,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 93,
    label = "CC[C](C)COO <=> OH + C1OC1(C)CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.4e+10,'1/s'), n=0.73, Ea=(12.459,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 94,
    label = "C[CH]C(C)COO <=> OH + CC1OCC1C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3e+09,'1/s'), n=0.84, Ea=(17.137,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 95,
    label = "[CH2]CC(C)COO <=> OH + CC1CCOC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41e+08,'1/s'), n=0.84, Ea=(11.715,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 96,
    label = "C2CCCOO <=> OH + O=CCC(C)C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(17700,'1/s'), n=2.58, Ea=(36.753,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 97,
    label = "CC(C)[CH]COO <=> OH + C1OC1C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.56e+11,'1/s'), n=0.59, Ea=(13.83,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 98,
    label = "C[C](C)CCOO <=> OH + O1CCC1(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.33e+07,'1/s'), n=1.16, Ea=(15.287,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 99,
    label = "C[C](C)CCOO <=> OH + iC4H8 + C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.35e+07,'1/s'), n=1.47, Ea=(29.962,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 100,
    label = "[CH2]C(C)CCOO <=> OH + CC1CCOC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.63e+08,'1/s'), n=0.89, Ea=(11.911,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 101,
    label = "iC5H11J-3 + O2 <=> iC5H11OOJ-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.83e-12*6.022e23,'cm^3/(mol*s)'), n=-0.47, Ea=(-1.239,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at MRCI(7e,5o)/CBS//CASSCF(7e,5o)/cc-pVDZ 1DHR from [4] by Ye et al.""",
)

entry(
    index = 102,
    label = "iC5H11OOJ-3 <=> CC(C)C([CH2])OO",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(12600,'1/s'), n=2.6, Ea=(29.755,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 103,
    label = "iC5H11OOJ-3 <=> C[C](C)C(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(67200,'1/s'), n=2.21, Ea=(25.647,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 104,
    label = "iC5H11OOJ-3 <=> [CH2]C(C)C(C)OO",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(253000,'1/s'), n=1.95, Ea=(20.961,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 105,
    label = "iC5H11OOJ-3 <=> OH + CC(C)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(177000,'1/s'), n=1.85, Ea=(36.239,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 106,
    label = "CC(C)C([CH2])OO <=> OH + C1OC1C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.98e+09,'1/s'), n=1.03, Ea=(13.191,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 107,
    label = "C[C](C)C(C)OO <=> OH + CC1OC1(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e+12,'1/s'), n=0.42, Ea=(10.506,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 108,
    label = "[CH2]C(C)C(C)OO <=> OH + CC1OCC1C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+09,'1/s'), n=0.85, Ea=(16.351,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 109,
    label = "iC5H11J-2 + O2 <=> iC5H11OOJ-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.49e-11*6.022e23,'cm^3/(mol*s)'), n=-0.6, Ea=(-1.531,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at MRCI(7e,5o)/CBS//CASSCF(7e,5o)/cc-pVDZ) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 110,
    label = "iC5H11OOJ-2 <=> CCC(C)([CH2])OO",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(152,'1/s'), n=2.99, Ea=(28.116,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 111,
    label = "iC5H11OOJ-2 <=> [CH2]CC(C)(C)OO",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(2240,'1/s'), n=2.4, Ea=(18.43,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 112,
    label = "iC5H11OOJ-2 <=> C[CH]C(C)(C)OO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(236,'1/s'), n=2.8, Ea=(24.854,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 113,
    label = "CCC(C)([CH2])OO <=> OH + C1OC1(C)CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.43e+10,'1/s'), n=0.75, Ea=(12.588,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 114,
    label = "[CH2]CC(C)(C)OO <=> OH + O1CCC1(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.36e+08,'1/s'), n=1.01, Ea=(17.108,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 115,
    label = "[CH2]CC(C)(C)OO <=> OH + C2H4 + CC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.41e+09,'1/s'), n=1.41, Ea=(24.198,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 116,
    label = "C[CH]C(C)(C)OO <=> OH + CC1OC1(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.21e+10,'1/s'), n=0.69, Ea=(11.244,'kcal/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1500,'K')),
    shortDesc = """calculated at QCISD(T)/CBS//B3LYP/6-311++G(d,p) 1DHR from [4] by Ye et al.""",
)

entry(
    index = 117,
    label = "C3H6 + O2 <=> [CH2]C=C + HO2",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(17.7,'cm^3/(mol*s)'), n=3.64, Ea=(37.3,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 118,
    label = "iC4H8 + O2 <=> [CH2]C(C)=C + HO2",
    degeneracy = 12.0,
    kinetics = Arrhenius(A=(1030,'cm^3/(mol*s)'), n=3.19, Ea=(37.9,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 119,
    label = "C4H8-2 + O2 <=> [CH2]C=CC + HO2",
    degeneracy = 12.0,
    kinetics = Arrhenius(A=(77.4,'cm^3/(mol*s)'), n=3.52, Ea=(36.2,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 120,
    label = "O1C(C)=CC=C1 + O2 <=> O1C([CH2])=CC=C1 + HO2",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(0.981,'cm^3/(mol*s)'), n=3.98, Ea=(37.4,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 121,
    label = "CC1=CC=CC=C1 + O2 <=> [CH2]C1=CC=CC=C1 + HO2",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(1010,'cm^3/(mol*s)'), n=3.24, Ea=(39.6,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 122,
    label = "C4H8-1 + O2 <=> [CH2]C=CC + HO2",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(48.8,'cm^3/(mol*s)'), n=3.48, Ea=(34.8,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 123,
    label = "C5H10-1 + O2 <=> C=C[CH]CC + HO2",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(60.6,'cm^3/(mol*s)'), n=3.45, Ea=(34.6,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 124,
    label = "O1C(CC)=CC=C1 + O2 <=> O1C([CH]C)=CC=C1 + HO2",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(19.5,'cm^3/(mol*s)'), n=3.52, Ea=(35.1,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 125,
    label = "CCC1=CC=CC=C1 + O2 <=> C[CH]C1=CC=CC=C1 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(427,'cm^3/(mol*s)'), n=3.11, Ea=(37.6,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 126,
    label = "CCCC1=CC=CC=C1 + O2 <=> CC[CH]C1=CC=CC=C1 + HO2",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1800,'cm^3/(mol*s)'), n=2.9, Ea=(37.7,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 127,
    label = "isopentene + O2 <=> C[C](C)C=C + HO2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(6020,'cm^3/(mol*s)'), n=3.03, Ea=(32.9,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 128,
    label = "O1C(C(C)C)=CC=C1 + O2 <=> O1C([C](C)C)=CC=C1 + HO2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2980,'cm^3/(mol*s)'), n=2.75, Ea=(32.5,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 129,
    label = "CC(C)C1=CC=CC=C1 + O2 <=> C[C](C)C1=CC=CC=C1 + HO2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(63900,'cm^3/(mol*s)'), n=2.47, Ea=(37,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 130,
    label = "C=CCC=C + O2 <=> C=C[CH]C=C + HO2",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(0.482,'cm^3/(mol*s)'), n=4.16, Ea=(29.9,'kcal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at G4//M06-2X/6-311++G(d,p) 1DHR from [5] by Zhou et al.""",
)

entry(
    index = 131,
    label = "H + C4H8-1 <=> C=[C]CC + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(211000,'cm^3/(mol*s)'), n=2.54, Ea=(40.67,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 132,
    label = "H + C2H4 <=> [CH2]C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.15e+15,'cm^3/(mol*s)'), n=-0.41, Ea=(14.73,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 133,
    label = "H + C3H6 <=> [CH2]CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.25e+15,'cm^3/(mol*s)'), n=-0.73, Ea=(19.34,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 134,
    label = "H + C3H6 <=> C[CH]C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.02e+14,'cm^3/(mol*s)'), n=-0.03, Ea=(11.43,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 135,
    label = "H + C4H8-1 <=> [CH2]CCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.23e+14,'cm^3/(mol*s)'), n=-0.27, Ea=(18.47,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 136,
    label = "H + C4H8-1 <=> C[CH]CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.06e+15,'cm^3/(mol*s)'), n=-0.6, Ea=(14.59,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 137,
    label = "H + C4H8-2 <=> C[CH]CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.56e+15,'cm^3/(mol*s)'), n=-0.42, Ea=(15.68,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 138,
    label = "H + iC4H8 <=> [CH2]C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.67e+13,'cm^3/(mol*s)'), n=-0.21, Ea=(22.08,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 139,
    label = "H + iC4H8 <=> C[C](C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.89e+15,'cm^3/(mol*s)'), n=-0.53, Ea=(11.98,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 140,
    label = "H + C2H4 <=> [CH]=C + H2",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(479000,'cm^3/(mol*s)'), n=2.55, Ea=(51.77,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 141,
    label = "H + C3H6 <=> [CH]=CC + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.12e+06,'cm^3/(mol*s)'), n=2.43, Ea=(53.96,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 142,
    label = "H + C3H6 <=> C=[C]C + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(311000,'cm^3/(mol*s)'), n=2.51, Ea=(40.36,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 143,
    label = "H + C3H6 <=> [CH2]C=C + H2",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(697,'cm^3/(mol*s)'), n=3.24, Ea=(13.93,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 144,
    label = "H + C4H8-1 <=> [CH]=CCC + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.01e+06,'cm^3/(mol*s)'), n=2.44, Ea=(54.53,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 145,
    label = "H + C4H8-1 <=> [CH2]C=CC + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(237000,'cm^3/(mol*s)'), n=2.56, Ea=(12.24,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 146,
    label = "H + C4H8-1 <=> C=CC[CH2] + H2",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(123000,'cm^3/(mol*s)'), n=2.71, Ea=(29.03,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 147,
    label = "H + C4H8-2 <=> [CH2]C=CC + H2",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(26000,'cm^3/(mol*s)'), n=2.95, Ea=(15.36,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 148,
    label = "H + C4H8-2 <=> C[C]=CC + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(12100,'cm^3/(mol*s)'), n=2.41, Ea=(43.19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 149,
    label = "H + iC4H8 <=> [CH2]C(C)=C + H2",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(4450,'cm^3/(mol*s)'), n=3.08, Ea=(14.81,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

entry(
    index = 150,
    label = "H + iC4H8 <=> [CH]=C(C)C + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.6e+06,'cm^3/(mol*s)'), n=2.34, Ea=(57.34,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    shortDesc = """calculated at CCSD(T)/CBS//wb97xd/aug-cc-PVTZ 1DHR(ωB97XD/6-311++G(d,p)) from [6] by Power et al.""",
)

