#!/usr/bin/env python
# encoding: utf-8

name = "1,2_Insertion_CO/groups"
shortDesc = ""
longDesc = """
Reaction site *1 should always be a singlet in this family.
"""

template(reactants=["Root"], products=["R_CO_R'"], ownReverse=False)

reverse = "1,1_Elimination"
reversible = True

reactantNum = 2
productNum = 1

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*4'],
    ['GAIN_PAIR', '*4', '1'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*1', 1, '*2'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['LOSE_PAIR', '*1', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 [H,Cs,Cd,Cb,Ct,CO,O,Sis,Sid,N,S] u0 {2,S}
2 *3 [H,Cs,Cd,Cb,Ct,Sis,Sid,N,S]      u0 {1,S}
3 *1 C                                u0 p1 c-1 {4,T}
4 *4 [O,S]                            u0 p1 c+1 {3,T}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_2CbCdCsCtHNSSidSis->H",
    group = 
"""
1 *2 [H,Cs,Cd,Cb,Ct,CO,O,Sis,Sid,N,S] u0 {2,S}
2 *3 H                                u0 {1,S}
3 *1 C                                u0 p1 c-1 {4,T}
4 *4 O                                u0 p1 c+1 {3,T}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_2CbCdCsCtHNSSidSis->H_1COCbCdCsCtHNOSSidSis->O",
    group = 
"""
1 *2 O u0 {2,S}
2 *3 H u0 {1,S}
3 *1 C u0 p1 c-1 {4,T}
4 *4 O u0 p1 c+1 {3,T}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O",
    group = 
"""
1 *2 [H,Cs] u0 {2,S}
2 *3 H      u0 {1,S}
3 *1 C      u0 p1 c-1 {4,T}
4 *4 O      u0 p1 c+1 {3,T}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_1CsH->H",
    group = 
"""
1 *2 H u0 r0 {2,S}
2 *3 H u0 r0 {1,S}
3 *1 C u0 p1 c-1 r0 {4,T}
4 *4 O u0 p1 c+1 r0 {3,T}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H",
    group = 
"""
1 *2 Cs u0 {2,S}
2 *3 H  u0 {1,S}
3 *1 C  u0 p1 c-1 {4,T}
4 *4 O  u0 p1 c+1 {3,T}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H_Ext-1Cs-R",
    group = 
"""
1 *2 Cs  u0 {2,S} {5,[S,D,T,B]}
2 *3 H   u0 {1,S}
3 *1 C   u0 p1 c-1 {4,T}
4 *4 O   u0 p1 c+1 {3,T}
5    R!H ux {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H_Ext-1Cs-R_Ext-1Cs-R",
    group = 
"""
1 *2 Cs  u0 {2,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 H   u0 {1,S}
3 *1 C   u0 p1 c-1 {4,T}
4 *4 O   u0 p1 c+1 {3,T}
5    R!H ux {1,[S,D,T,B]}
6    R!H ux {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H_Ext-1Cs-R_Ext-1Cs-R_Ext-1Cs-R",
    group = 
"""
1 *2 Cs  u0 {2,S} {5,[S,D,T,B]} {6,[S,D,T,B]} {7,[S,D,T,B]}
2 *3 H   u0 {1,S}
3 *1 C   u0 p1 c-1 {4,T}
4 *4 O   u0 p1 c+1 {3,T}
5    R!H ux {1,[S,D,T,B]}
6    R!H ux {1,[S,D,T,B]}
7    R!H ux {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-2CbCdCsCtHNSSidSis->H",
    group = 
"""
1 *2 [H,Cs,Cd,Cb,Ct,CO,O,Sis,Sid,N,S] u0 r0 {2,S}
2 *3 [Cb,Sis,Sid,Cd,Cs,S,Ct,N]        u0 r0 {1,S}
3 *1 C                                u0 p1 c-1 r0 {4,T}
4 *4 O                                u0 p1 c+1 r0 {3,T}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_2CbCdCsCtHNSSidSis->H
        L3: Root_2CbCdCsCtHNSSidSis->H_1COCbCdCsCtHNOSSidSis->O
        L3: Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O
            L4: Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_1CsH->H
            L4: Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H
                L5: Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H_Ext-1Cs-R
                    L6: Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H_Ext-1Cs-R_Ext-1Cs-R
                        L7: Root_2CbCdCsCtHNSSidSis->H_N-1COCbCdCsCtHNOSSidSis->O_N-1CsH->H_Ext-1Cs-R_Ext-1Cs-R_Ext-1Cs-R
    L2: Root_N-2CbCdCsCtHNSSidSis->H
"""
)

